### ISSUE TITLE
Pickling of functions in a file loaded in a Sage Worksheet fails

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#2]
Somebody (not me) reported this:

Below is a small example demonstrating the issue:
- First create a file called `test.py` with the following content:

``` python
def test_function(): pass
```
- Next open a Sage Worksheet and execute the following code:

``` python
load('test.py')
save(test_function, 'test.sobj')
```
- This crashes with the following traceback:

```
Error in lines 1-1
Traceback (most recent call last):
  File "/projects/8d39729d-4566-4056-84e2-c636147c3fc3/.sagemathcloud/sage_server.py", line 879, in execute
    exec compile(block+'\n', '', 'single') in namespace, locals
  File "", line 1, in <module>
  File "sage/structure/sage_object.pyx", line 989, in sage.structure.sage_object.save (build/cythonized/sage/structure/sage_object.c:11348)
    s = cPickle.dumps(obj, protocol=2)
TypeError: expected string or Unicode object, NoneType found
```
- Switching to `pickle` instead of `cPickle` makes it more obvious what the issue is:

``` python
import pickle
pickle.dumps(test_function, protocol=2)
```

which crashes with the following traceback:

```
Error in lines 2-2
Traceback (most recent call last):
  File "/projects/8d39729d-4566-4056-84e2-c636147c3fc3/.sagemathcloud/sage_server.py", line 879, in execute
    exec compile(block+'\n', '', 'single') in namespace, locals
  File "", line 1, in <module>
  File "/projects/sage/sage-6.7/local/lib/python/pickle.py", line 1374, in dumps
    Pickler(file, protocol).dump(obj)
  File "/projects/sage/sage-6.7/local/lib/python/pickle.py", line 224, in dump
    self.save(obj)
  File "/projects/sage/sage-6.7/local/lib/python/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/projects/sage/sage-6.7/local/lib/python/pickle.py", line 748, in save_global
    (obj, module, name))
PicklingError: Can't pickle <function test_function at 0x7f1af4bdccf8>: it's not found as __main__.test_function
```

If you try the same thing in command-line Sage, then everything works as you would expect.

**Comment by DrXyzzy** [comment]
Problem occurs with functions and classes defined at top level in worksheet as well as loaded from file:

function:
```
import pickle
def f():
    pass
s = pickle.dumps(f, protocol = 2)
==>
PicklingError: Can't pickle <function f at 0x7f1ebb091500>: it's not found as __main__.f
```
class:
```
class Klas():
    def kf():
        pass
sk = pickle.dumps(Klas, protocol = 2)
==>
PicklingError: Can't pickle <class __builtin__.Klas at 0x7f1eba3e1a10>: it's not found as __builtin__.Klas
```

**Comment by DrXyzzy** [comment]
WON'T FIX.

Decided not to deploy a fix for this problem, because there is negligible value to saving/pickling a top-level function or class definition at the cost of complexity added. See last few paragraphs here: [What can be pickled and unpickled?](https://docs.python.org/2/library/pickle.html#what-can-be-pickled-and-unpickled)

A workaround function to save a function or class at top level is here, in case it is needed in some edge case:
https://github.com/sagemathinc/smc/pull/715/commits/76c386bebc97d8db1df8c2a3606afa6a4af3553b

**Comment by haraldschilly** [comment]
Despite the "wont fix", I'm reopening this. It's unexpected "buggy" behavior, and it's 100% caused by the sagews layer. 

Dear future reader: you can use a jupyter sage kernel  talking "more directly" with sage. then this works.

**Comment by DrXyzzy** [comment]
@haraldschilly:

Comment from @williamstein on 2016-07-22 was that the proposed fix was not useful in any real-life situation and should therefore be reverted. So I think we have working code, the decision was whether to deploy it.
