### ISSUE TITLE
traceback in hub

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#2203]
Traceback in backend hub (only one in about 2 weeks, and only happened once):

```
2017-07-13 21:29:34.934031 | 3 days 20:41:09.138177  | uncaught_exception | {"host": "smc-hub-2860007680-1xs5s", "error": "Error: invalid
 account_id (='undefined') or project_id (='dbb76524-33d2-4096-b716-7853b4e6aaef')", "stack": "Error: invalid account_id (='undefined') or
 project_id (='dbb76524-33d2-4096-b716-7853b4e6aaef')\n    at Error (native)\n    at ProjectAndUserTracker._add_user_to_project (/cocalc/s
rc/smc-hub/postgres-synctable.coffee:286:19)\n    at ProjectAndUserTracker._add_user_to_project (/cocalc/src/smc-hub/postgres-synctable.co
ffee:22:1)\n    at /cocalc/src/smc-hub/postgres-synctable.coffee:383:38\n    at Object.cb (/cocalc/src/smc-hub/postgres-base.coffee:1118:1
7)\n    at .callback (/cocalc/src/smc-hub/postgres-base.coffee:517:22)\n    at after (/cocalc/src/smc-hub/node_modules/pg/lib/native/query
.js:103:12)\n    at onResult (/cocalc/src/smc-hub/node_modules/pg-native/index.js:167:5)\n    at g (events.js:292:16)\n    at emitOne (eve
nts.js:96:13)\n    at emit (events.js:188:7)\n    at Client._read (/cocalc/src/smc-hub/node_modules/pg-native/index.js:127:12)\n    at emi
tNone (events.js:86:13)\n    at PQ.emit (events.js:185:7)\n"}
```

**Comment by williamstein** [comment]
This must be old code running on the storage servers (which I haven’t restarted in forever); will be deprecated soon due to kucalc switch anyways.  closing.
