### ISSUE TITLE
bug in project's local_hub

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#2297]
While investigating some startup problems in kucalc, I saw these exceptions a lot of times. Maybe they're caused by a problematic process spawning earlier in the code. Still, in any case this shouldn't happen.

logfile:

```
2017-08-16T13:59:49.228Z - debug: open_syncstrings: 0; recent_syncstrings: 0
2017-08-16T14:00:04.985Z - debug: Client.update_status:
2017-08-16T14:00:05.093Z - debug: Client.call(message={"id":"1f076da6-1318-4109-9b04-a94638a90856","query":{"projects":{"project_id":"732b7447-0839-418b-a57d-2e3d8a7bb3fc","status":{"memory":{"rss
":136076},"disk_MB":1}}},"multi_response":false,"event":"query"}):
2017-08-16T14:00:05.093Z - debug: Client.call(message={"id":"1f076da6-1318-4109-9b04-a94638a90856","query":{"projects":{"project_id":"732b7447-0839-418b-a57d-2e3d8a7bb3fc","status":{"memory":{"rss
":136076},"disk_MB":1}}},"multi_response":false,"event":"query"}): configure timeout
2017-08-16T14:00:05.142Z - debug: Client.handle_mesg({"id":"1f076da6-1318-4109-9b04-a94638a90856","query":{},"multi_response":false,"event":"query"}): calling callback
2017-08-16T14:00:34.987Z - debug: Client.update_status:
2017-08-16T14:00:34.999Z - debug: BUG ****************************************************************************
2017-08-16T14:00:34.999Z - debug: Uncaught exception: TypeError: Cannot read property 'on' of undefined
2017-08-16T14:00:35.001Z - debug: TypeError: Cannot read property 'on' of undefined
    at async.series.exit_code (/cocalc/src/smc-util-node/misc_node.js:511:17)
    at /cocalc/src/smc-util-node/node_modules/async/lib/async.js:718:13
    at iterate (/cocalc/src/smc-util-node/node_modules/async/lib/async.js:262:13)
    at /cocalc/src/smc-util-node/node_modules/async/lib/async.js:274:29
    at /cocalc/src/smc-util-node/node_modules/async/lib/async.js:44:16
    at /cocalc/src/smc-util-node/node_modules/async/lib/async.js:723:17
    at /cocalc/src/smc-util-node/node_modules/async/lib/async.js:167:37
    at FSReqWrap.oncomplete (fs.js:123:15)
 
2017-08-16T14:00:35.001Z - debug: BUG ****************************************************************************
Trace
    at process.<anonymous> (/cocalc/src/smc-project/local_hub.js:29:22)
    at emitOne (events.js:101:20)
    at process.emit (events.js:188:7)
    at process._fatalException (bootstrap_node.js:296:26)
```

The JS code in misc_node.js line 511 is: 

```
        if (opts.verbose) {
          winston.debug("Listen for stdout, stderr and exit events.");
        }
        stdout = '';
        r.stdout.on('data', function(data) {         <==== FAIL
          data = data.toString();
          if (opts.max_output != null) {
            if (stdout.length < opts.max_output) {
              return stdout += data.slice(0, opts.max_output - stdout.length);
            }
```

which is easy to spot in the coffee file and implicates, that `r = child_process.spawn(opts.command, opts.args, o)` does NOT fail, but `r.stdout` doesn't exist.

**Comment by haraldschilly** [comment]
This is hopfully taken care by https://github.com/sagemathinc/cocalc/commit/12ec99bc401bbf38eacda59b1d979b1c13bfe538
