### ISSUE TITLE
sagews %sh mode fails in kucalc, kernel dies

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#2311]
Open .sagews in kucalc(2) and see the following:
_Note: the bash kernel starts ok with jupyter2 in kucalc_

```
%sh date
  ==>
Error in lines 1-1
Traceback (most recent call last):
  File "/cocalc/lib/python2.7/site-packages/smc_sagews/sage_server.py", line 995, in execute
    exec compile(block+'\n', '', 'single') in namespace, locals
  File "", line 1, in <module>
  File "/cocalc/lib/python2.7/site-packages/smc_sagews/sage_server.py", line 1040, in execute_with_code_decorators
    code = code_decorator(code)
  File "/cocalc/lib/python2.7/site-packages/smc_sagews/sage_salvus.py", line 2098, in sh
    sh.jupyter_kernel = jupyter("bash")
  File "/cocalc/lib/python2.7/site-packages/smc_sagews/sage_jupyter.py", line 33, in __call__
    return _jkmagic(kernel_name, **kwargs)
  File "/cocalc/lib/python2.7/site-packages/smc_sagews/sage_jupyter.py", line 115, in _jkmagic
    km, kc = jupyter_client.manager.start_new_kernel(kernel_name = kernel_name)
  File "/ext/sage/sage-8.0/local/lib/python2.7/site-packages/jupyter_client/manager.py", line 433, in start_new_kernel
    kc.wait_for_ready(timeout=startup_timeout)
  File "/ext/sage/sage-8.0/local/lib/python2.7/site-packages/jupyter_client/blocking/client.py", line 59, in wait_for_ready
    raise RuntimeError('Kernel died before replying to kernel_info')
RuntimeError: Kernel died before replying to kernel_info
```

**Comment by williamstein** [comment]
Currently in KuCalc this is replaced by something MUCH worse -- absolutely all of the Jupyter kernel bridges immediately fail with:
```
Error in lines 1-1
Traceback (most recent call last):
  File "/cocalc/lib/python2.7/site-packages/smc_sagews/sage_server.py", line 995, in execute
    exec compile(block+'\n', '', 'single') in namespace, locals
  File "", line 1, in <module>
  File "/cocalc/lib/python2.7/site-packages/smc_sagews/sage_jupyter.py", line 33, in __call__
    return _jkmagic(kernel_name, **kwargs)
  File "/cocalc/lib/python2.7/site-packages/smc_sagews/sage_jupyter.py", line 115, in _jkmagic
    km, kc = jupyter_client.manager.start_new_kernel(kernel_name = kernel_name)
  File "/ext/sage/sage-8.0/local/lib/python2.7/site-packages/jupyter_client/manager.py", line 429, in start_new_kernel
    km.start_kernel(**kwargs)
  File "/ext/sage/sage-8.0/local/lib/python2.7/site-packages/jupyter_client/manager.py", line 230, in start_kernel
    kernel_cmd = self.format_kernel_cmd(extra_arguments=extra_arguments)
  File "/ext/sage/sage-8.0/local/lib/python2.7/site-packages/jupyter_client/manager.py", line 170, in format_kernel_cmd
    cmd = self.kernel_spec.argv + extra_arguments
  File "/ext/sage/sage-8.0/local/lib/python2.7/site-packages/jupyter_client/manager.py", line 82, in kernel_spec
    self._kernel_spec = self.kernel_spec_manager.get_kernel_spec(self.kernel_name)
  File "/ext/sage/sage-8.0/local/lib/python2.7/site-packages/jupyter_client/kernelspec.py", line 171, in get_kernel_spec
    d = self.find_kernel_specs()
  File "/ext/sage/sage-8.0/local/lib/python2.7/site-packages/jupyter_client/kernelspec.py", line 128, in find_kernel_specs
    for kernel_dir in self.kernel_dirs:
  File "/ext/sage/sage-8.0/local/lib/python2.7/site-packages/traitlets/traitlets.py", line 554, in __get__
    return self.get(obj, cls)
  File "/ext/sage/sage-8.0/local/lib/python2.7/site-packages/traitlets/traitlets.py", line 533, in get
    value = self._validate(obj, dynamic_default())
  File "/ext/sage/sage-8.0/local/lib/python2.7/site-packages/jupyter_client/kernelspec.py", line 114, in _kernel_dirs_default
    from IPython.paths import get_ipython_dir
  File "/ext/sage/sage-8.0/local/lib/python2.7/site-packages/IPython/__init__.py", line 49, in <module>
    from .terminal.embed import embed
  File "/ext/sage/sage-8.0/local/lib/python2.7/site-packages/IPython/terminal/embed.py", line 17, in <module>
    from IPython.terminal.interactiveshell import TerminalInteractiveShell
  File "/ext/sage/sage-8.0/local/lib/python2.7/site-packages/IPython/terminal/interactiveshell.py", line 29, in <module>
    from .magics import TerminalMagics
  File "/ext/sage/sage-8.0/local/lib/python2.7/site-packages/IPython/terminal/magics.py", line 15, in <module>
    from IPython.lib.clipboard import ClipboardEmpty
  File "/ext/sage/sage-8.0/local/lib/python2.7/site-packages/IPython/lib/clipboard.py", line 7, in <module>
    import IPython.utils.py3compat as py3compat
AttributeError: 'module' object has no attribute 'utils'
```

**Comment by williamstein** [comment]
The Jupyter install is fundamentally broke or mis-installed in sage-8.0. Even on the command line:

Do
```
sage -sh
jupyter console —kernel=bash
```

And get
```
ext/sage/sage-8.0/local/bin/python3: No module named bash_kernel
 
Traceback (most recent call last):
  File "/ext/sage/sage-8.0/local/bin/jupyter-console", line 11, in <module>
    sys.exit(main())
  File "/ext/sage/sage-8.0/local/lib/python2.7/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/ext/sage/sage-8.0/local/lib/python2.7/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-113>", line 2, in initialize
  File "/ext/sage/sage-8.0/local/lib/python2.7/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/ext/sage/sage-8.0/local/lib/python2.7/site-packages/jupyter_console/app.py", line 141, in initialize
    self.init_shell()
  File "/ext/sage/sage-8.0/local/lib/python2.7/site-packages/jupyter_console/app.py", line 114, in init_shell
    client=self.kernel_client,
  File "/ext/sage/sage-8.0/local/lib/python2.7/site-packages/traitlets/config/configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "/ext/sage/sage-8.0/local/lib/python2.7/site-packages/jupyter_console/ptshell.py", line 270, in __init__
    self.init_kernel_info()
  File "/ext/sage/sage-8.0/local/lib/python2.7/site-packages/jupyter_console/ptshell.py", line 324, in init_kernel_info
    raise RuntimeError("Kernel didn't respond to kernel_info_request")
RuntimeError: Kernel didn't respond to kernel_info_request
```

**Comment by williamstein** [comment]
Also broken in sage-7.6:
```
~$ sage-7.6 -sh
sage-sh) user@project-8b023cad-4800-46a5-a5c8-f54aeb37eb72:~$ jupyter  console --kernel=bash
/ext/sage/sage-7.6/local/bin/python3: No module named bash_kernel
 ```

**Comment by haraldschilly** [comment]
argh! I'll delete the "python3" executable... that did help in the past

**Comment by williamstein** [comment]
Yes, this is a problem with all the sage executables (also 7.6 etc.) and it’s still not fixed as I test right now.

**Comment by williamstein** [comment]
Closing, this was all the stupid python3 that is in sage.  I'm also going to complain on sage-devel.
