### ISSUE TITLE
kucalc sagews pytest failure

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#2312]
sagews pytest file fails in kucalc (passes in classic with `53 passed, 5 skipped in 40.65 seconds`)

in kucalc:
```
$ grep "^__version__" /usr/local/lib/python2.7/dist-packages/OpenSSL/version.py
__version__ = '0.15.1'
```

in classic:
```
$ grep "^__version__" /usr/local/lib/python2.7/dist-packages/OpenSSL/version.py
__version__ = "16.2.0"
```

```
~/cocalc/src/smc_sagews/smc_sagews/tests$ python -m pytest test_sagews.py
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/pytest.py", line 73, in <module>
    raise SystemExit(pytest.main())
  File "/usr/local/lib/python2.7/dist-packages/_pytest/config.py", line 49, in main
    config = _prepareconfig(args, plugins)
  File "/usr/local/lib/python2.7/dist-packages/_pytest/config.py", line 168, in _prepareconfig
    pluginmanager=pluginmanager, args=args)
  File "/usr/local/lib/python2.7/dist-packages/_pytest/vendored_packages/pluggy.py", line 745, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File "/usr/local/lib/python2.7/dist-packages/_pytest/vendored_packages/pluggy.py", line 613, in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
  File "/usr/local/lib/python2.7/dist-packages/_pytest/vendored_packages/pluggy.py", line 250, in _wrapped_call
    wrap_controller.send(call_outcome)
  File "/usr/local/lib/python2.7/dist-packages/_pytest/helpconfig.py", line 68, in pytest_cmdline_parse
    config = outcome.get_result()
  File "/usr/local/lib/python2.7/dist-packages/_pytest/vendored_packages/pluggy.py", line 280, in get_result
    _reraise(*ex)  # noqa
  File "/usr/local/lib/python2.7/dist-packages/_pytest/vendored_packages/pluggy.py", line 265, in __init__
    self.result = func()
  File "/usr/local/lib/python2.7/dist-packages/_pytest/vendored_packages/pluggy.py", line 614, in execute
    res = hook_impl.function(*args)
  File "/usr/local/lib/python2.7/dist-packages/_pytest/config.py", line 957, in pytest_cmdline_parse
    self.parse(args)
  File "/usr/local/lib/python2.7/dist-packages/_pytest/vendored_packages/pluggy.py", line 510, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2316, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2322, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/_pytest/assertion/rewrite.py", line 212, in load_module
    py.builtin.exec_(co, mod.__dict__)
  File "/usr/local/lib/python2.7/dist-packages/py/_builtin.py", line 221, in exec_
    exec2(obj, globals, locals)
  File "<string>", line 7, in exec2
  File "/usr/local/lib/python2.7/dist-packages/pytest_selenium/drivers/crossbrowsertesting.py", line 7, in <module>
    import requests
  File "/usr/local/lib/python2.7/dist-packages/requests/__init__.py", line 84, in <module>
    from urllib3.contrib import pyopenssl
  File "/usr/local/lib/python2.7/dist-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 118, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'
```

**Comment by haraldschilly** [comment]
Hi, I'm aware of that, and well, I think we can close it. 

Usually you run the tests via python3 anyways, right?

**Comment by DrXyzzy** [comment]
I have been running the tests with python2. I just tried `python3 -m pytest test_sagews.py` in latest cocalc master _(is that the right branch to test on?)_ and got `TypeError: 'str' does not support the buffer interface` in the test configuration setup, all tests failing. I'll have a look at it.

**Comment by haraldschilly** [comment]
Hmm, I don't know, I'm working on creating updated and newer images for kucalc, maybe I am able to figure out what's really going on with these pyOpenSSL errors...

Long term, I think it's better to stick with the python3 version of pytests.

**Comment by DrXyzzy** [comment]
I started fixing the byte vs. string issues to move pytest to python 3 and realized I was not doing it right. Will try again soon. Looks doable. Also items() vs iteritems().

**Comment by DrXyzzy** [comment]
closing for now because the sagews pytest suite is running with python2 again
