### ISSUE TITLE
hub: exception setting quota memory limit

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#2421]
This is in smc-hub/kucalc/quota.coffee and trivial to fix.

```
2017-10-09T19:46:43.441Z - debug: BUG ****************************************************************************
2017-10-09T19:46:43.441Z - debug: Uncaught exception: ReferenceError: MEMORY_REQUEST_MIN is not defined
2017-10-09T19:46:43.467Z - debug: ReferenceError: MEMORY_REQUEST_MIN is not defined
    at Object.exports.quota (/cocalc/src/smc-hub/kucalc/quota.js:75:39)
    at database.get_project.cb (/cocalc/src/smc-hub/kucalc/compute-client.js:832:33)
    at Object.cb (/cocalc/src/smc-hub/postgres-base.js:1575:13)
    at Result.callback (/cocalc/src/smc-hub/postgres-base.js:699:20)
    at after (/cocalc/src/smc-hub/node_modules/pg/lib/native/query.js:125:12)
    at onResult (/cocalc/src/smc-hub/node_modules/pg-native/index.js:167:5)
    at g (events.js:292:16)
    at emitOne (events.js:96:13)
    at emit (events.js:188:7)
    at Client._read (/cocalc/src/smc-hub/node_modules/pg-native/index.js:127:12)
    at emitNone (events.js:86:13)
    at PQ.emit (events.js:185:7)

2017-10-09T19:46:43.467Z - debug: BUG ****************************************************************************
```

**Comment by williamstein** [comment]
I already fixed this and pushed the fix to master before you created this issue.
