### ISSUE TITLE
hub exception: TypeError: Cannot read property 'end' of undefined

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#2656]
saw several instances of this in the hub-api `7kx63` on node `teea`

```
2018-01-22T13:12:35.836Z - ESC[34mdebugESC[39m: PostgreSQL._query('SELECT NOW()',id='c14999'): "query='SELECT NOW() (concurrent=1)'"
2018-01-22T13:12:35.837Z - ESC[34mdebugESC[39m: PostgreSQL._query('SELECT NOW()',id='c14999'): "done (concurrent=0) (query_time_ms=0) -- success"
2018-01-22T13:12:35.837Z - ESC[34mdebugESC[39m: PostgreSQL.test_query: "finished"
2018-01-22T13:12:49.119Z - ESC[34mdebugESC[39m: API.http_message_api_v1:  event= query body= projects=[state=null, description=null, title=null, deleted=null, project_id=null, last_edited=null]
2018-01-22T13:12:49.119Z - ESC[34mdebugESC[39m: PostgreSQL._query('SELECT account_id FROM accounts',id='779f3b'): "query='SELECT account_id FROM accounts WHERE api_key = $1::TEXT (concurrent=1)'"
2018-01-22T13:12:49.120Z - ESC[34mdebugESC[39m: PostgreSQL._query('SELECT account_id FROM accounts',id='779f3b'): "done (concurrent=0) (query_time_ms=0) -- success"
2018-01-22T13:12:49.121Z - ESC[34mdebugESC[39m: API.handle_message:  { query: { projects: [ [Object] ] },
  multi_response: false,
  event: 'query',
  id: 'fa0efbd3-b61c-4704-a6f2-a2975f77ed96' } 18743750-d243-4ad1-9f71-2f392295706c
2018-01-22T13:12:49.121Z - ESC[34mdebugESC[39m: PostgreSQL.user_query_queue: "user_query(client_id='18743750-d243-4ad1-9f71-2f392295706c')"
2018-01-22T13:12:49.121Z - ESC[34mdebugESC[39m: PostgreSQL.user_query_queue: "client_id='18743750-d243-4ad1-9f71-2f392295706c': avg=0ms, count(local=1,global=1), queued.length=0, sent=1"
2018-01-22T13:12:49.122Z - ESC[34mdebugESC[39m: PostgreSQL.user_query_queue: "_do_one_query(client_id='18743750-d243-4ad1-9f71-2f392295706c') -- doing the query"
2018-01-22T13:12:49.122Z - ESC[34mdebugESC[39m: PostgreSQL.user_get_query(table='projects'): "account_id='undefined', project_id='undefined', query={\"state\":null,\"description\":null,\"title\":null,\"deleted\":null,\"project_id\":null,\"last_edited\":null}, multi=true, options=[],
 changes=undefined"
2018-01-22T13:12:49.122Z - ESC[34mdebugESC[39m: PostgreSQL.user_query_queue: "client_id='18743750-d243-4ad1-9f71-2f392295706c': avg=0ms, count(local=0,global=0), queued.length=0, sent=1"
2018-01-22T13:12:49.122Z - ESC[34mdebugESC[39m: Client(18743750-d243-4ad1-9f71-2f392295706c).user_query: ["user_query(query='{\"projects\":[{\"state\":null,\"description\":null,\"title\":null,\"deleted\":null,\"project_id\":null,\"last_edited\":null}]}') error:","FATAL: anonymous ge
t queries not allowed for table 'projects'"]
2018-01-22T13:12:49.122Z - ESC[34mdebugESC[39m: Client(18743750-d243-4ad1-9f71-2f392295706c).user_query: ["immediately terminating buggy client trying to do FATAL user_query when not signed_in"]
2018-01-22T13:12:49.296Z - ESC[34mdebugESC[39m: BUG ****************************************************************************
2018-01-22T13:12:49.296Z - ESC[34mdebugESC[39m: Uncaught exception: TypeError: Cannot read property 'end' of undefined
2018-01-22T13:12:49.325Z - ESC[34mdebugESC[39m: TypeError: Cannot read property 'end' of undefined
    at database.user_query.cb (/cocalc/src/smc-hub/client.js:2407:28)
    at Object.cb (/cocalc/src/smc-hub/postgres-user-query-queue.js:133:50)
    at Object.user_get_query.cb (/cocalc/src/smc-hub/postgres-user-queries.js:278:61)
    at PostgreSQL.exports.PostgreSQL.PostgreSQL.user_get_query (/cocalc/src/smc-hub/postgres-user-queries.js:1919:14)
    at PostgreSQL.user_get_query (/cocalc/src/smc-hub/postgres-user-queries.js:12:59)
    at PostgreSQL.exports.PostgreSQL.PostgreSQL._user_query (/cocalc/src/smc-hub/postgres-user-queries.js:264:23)
    at UserQueryQueue._do_query (/cocalc/src/smc-hub/postgres-user-queries.js:12:59)
    at UserQueryQueue.exports.UserQueryQueue.UserQueryQueue._do_one_query (/cocalc/src/smc-hub/postgres-user-query-queue.js:137:19)
    at UserQueryQueue._do_one_query (/cocalc/src/smc-hub/postgres-user-query-queue.js:5:59)
    at UserQueryQueue.exports.UserQueryQueue.UserQueryQueue._process_next_call (/cocalc/src/smc-hub/postgres-user-query-queue.js:162:19)
    at UserQueryQueue._process_next_call (/cocalc/src/smc-hub/postgres-user-query-queue.js:5:59)
    at UserQueryQueue.exports.UserQueryQueue.UserQueryQueue._update (/cocalc/src/smc-hub/postgres-user-query-queue.js:144:27)
    at UserQueryQueue._update (/cocalc/src/smc-hub/postgres-user-query-queue.js:5:59)
    at UserQueryQueue.exports.UserQueryQueue.UserQueryQueue.user_query (/cocalc/src/smc-hub/postgres-user-query-queue.js:105:19)
    at UserQueryQueue.user_query (/cocalc/src/smc-hub/postgres-user-query-queue.js:5:59)
    at PostgreSQL.exports.PostgreSQL.PostgreSQL.user_query (/cocalc/src/smc-hub/postgres-user-queries.js:130:37)
    at PostgreSQL.user_query (/cocalc/src/smc-hub/postgres-user-queries.js:12:59)
    at APIClient.exports.Client.Client.mesg_query (/cocalc/src/smc-hub/client.js:2388:28)
    at /cocalc/src/smc-hub/client.js:9:59
    at handle_message (/cocalc/src/smc-hub/api/handler.js:195:12)
    at /cocalc/src/smc-hub/api/handler.js:107:16
    at /cocalc/src/smc-hub/node_modules/async/lib/async.js:718:13
    at iterate (/cocalc/src/smc-hub/node_modules/async/lib/async.js:262:13)
    at /cocalc/src/smc-hub/node_modules/async/lib/async.js:274:29
    at /cocalc/src/smc-hub/node_modules/async/lib/async.js:44:16
    at /cocalc/src/smc-hub/node_modules/async/lib/async.js:723:17
    at /cocalc/src/smc-hub/node_modules/async/lib/async.js:167:37
    at Object.cb (/cocalc/src/smc-hub/api/handler.js:103:20)
    at /cocalc/src/smc-hub/api/handler.js:172:19
    at /cocalc/src/smc-hub/node_modules/async/lib/async.js:726:13
    at /cocalc/src/smc-hub/node_modules/async/lib/async.js:52:16
    at /cocalc/src/smc-hub/node_modules/async/lib/async.js:269:32
    at /cocalc/src/smc-hub/node_modules/async/lib/async.js:44:16
    at /cocalc/src/smc-hub/node_modules/async/lib/async.js:723:17
    at /cocalc/src/smc-hub/node_modules/async/lib/async.js:167:37
    at Object.cb (/cocalc/src/smc-hub/api/handler.js:152:24)
    at /cocalc/src/smc-hub/postgres-server-queries.js:457:25
    at Object.cb (/cocalc/src/smc-hub/postgres-base.js:1627:18)
    at Result.callback (/cocalc/src/smc-hub/postgres-base.js:755:20)
    at after (/cocalc/src/smc-hub/node_modules/pg/lib/native/query.js:125:12)
    at module.exports.onResult (/cocalc/src/smc-hub/node_modules/pg-native/index.js:167:5)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at module.exports.emit (events.js:211:7)
    at module.exports.Client._read (/cocalc/src/smc-hub/node_modules/pg-native/index.js:127:12)
    at emitNone (events.js:106:13)
    at PQ.emit (events.js:208:7)

2018-01-22T13:12:49.326Z - ESC[34mdebugESC[39m: BUG ****************************************************************************
2018-01-22T13:12:49.481Z - ESC[34mdebugESC[39m: PostgreSQL._query('INSERT INTO central_log',id='caaecf'): "query='INSERT INTO central_log (\"id\",\"event\",\"value\",\"time\") VALUES  ($1::UUID,$2::TEXT,$3::JSONB,$4::TIMESTAMP)  (concurrent=1)'"
2018-01-22T13:12:49.481Z - ESC[34mdebugESC[39m: BLOCKED for 359ms
2018-01-22T13:12:49.484Z - ESC[34mdebugESC[39m: PostgreSQL._query('INSERT INTO central_log',id='caaecf'): "done (concurrent=0) (query_time_ms=3) -- success"
2018-01-22T13:12:59.107Z - ESC[34mdebugESC[39m: API.http_message_api_v1:  event= query body= projects=[state=null, description=null, title=null, deleted=null, project_id=null, last_edited=null]
2018-01-22T13:12:59.107Z - ESC[34mdebugESC[39m: PostgreSQL._query('SELECT account_id FROM accounts',id='2596c5'): "query='SELECT account_id FROM accounts WHERE api_key = $1::TEXT (concurrent=1)'"
2018-01-22T13:12:59.109Z - ESC[34mdebugESC[39m: PostgreSQL._query('SELECT account_id FROM accounts',id='2596c5'): "done (concurrent=0) (query_time_ms=2) -- success"
```

**Comment by haraldschilly** [comment]
Hmm, looks like someone tries to do something with the hub api, but it fails. I think it is this code snippet in client.coffee:

```
                    if not @account_id? and misc.startswith("#{err}", "FATAL")
                        # Tried to do a user_query before signing in.  Since we no longer have any anonymous user queries
                        # there is absolutely no situation where a client should do this, unless it is buggy.
                        dbg("immediately terminating buggy client trying to do FATAL user_query when not signed_in")
                        @conn.end()      <===========
                        return
``` 

I don't know if `@conn.end()` should always be defined. I that case here, probably not.
