### ISSUE TITLE
Failed to exec install-all script

### ISSUE THREAD

**Issue by shinytang6** [sagemathinc/cocalc#2674]
Hi! Hope somebody can help me with problem.

There was an issue when i tried to use npm install dependencies on windows.

The err logs:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'install-all' ]
2 info using npm@5.6.0
3 info using node@v8.9.4
4 verbose run-script [ 'preinstall-all', 'install-all', 'postinstall-all' ]
5 info lifecycle cocalc@1.0.0~preinstall-all: cocalc@1.0.0
6 info lifecycle cocalc@1.0.0~install-all: cocalc@1.0.0
7 verbose lifecycle cocalc@1.0.0~install-all: unsafe-perm in lifecycle true
8 verbose lifecycle cocalc@1.0.0~install-all: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;G:\opensource\cocalc\src\node_modules\.bin;G:\JavaJDK\bin;G:\JavaJDK\jre\bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\nodejs;C:\Program Files\MongoDB\Server\3.4\bin;C:\Program Files\MySQL\MySQL Server 5.7\bin;F:\httpd-2.4.25-win64-VC14\Apache24\bin;G:\Golang\bin;G:\GoDev\bin;G:\Ruff\bin;C:\Program Files\nodejs\node_global;F:\Git\cmd;C:\Windows\System32;G:\apache-maven-3.5.0-bin\apache-maven-3.5.0\bin;C:\Windows;C:\Windows\system32\wbem;G:\CTEX\UserData\miktex\bin;G:\CTEX\MiKTeX\miktex\bin;G:\CTEX\CTeX\ctex\bin;G:\CTEX\CTeX\cct\bin;G:\CTEX\CTeX\ty\bin;G:\CTEX\Ghostscript\gs9.05\bin;G:\CTEX\GSview\gsview;G:\CTEX\WinEdt;F:\php-5.6.29-Win32-VC11-x64;C:\ProgramData\ComposerSetup\bin;C:\Users\亮\Desktop\超级优秀个人总结文件-满满的经验总结\ffmpeg-3.4-win64-static\ffmpeg-3.4-win64-static\bin;G:\VS2010\VC\bin;G:\speech2017b\HTK-3.4.1\htk\bin.win32;G:\HashiCorp\Vagrant\bin;F:\Git\bin;G:\make;C:\Program Files\nodejs\;C:\Python35\Scripts\;C:\Python35\;C:\Users\亮\AppData\Local\Programs\Python\Python35\Scripts\;:\Users\亮\AppData\Local\Programs\Python\Python35\;:\Users\亮\AppData\Roaming\npm;:\Program Files\Heroku\bin;G:\bin;C:\Users\亮\AppData\Roaming\Composer\vendor\bin;C:\Users\亮\AppData\Local\GitHubDesktop\bin;G:\DSD\modeltech64_10.1c\win64;G:\DSD\modeltech64_10.4\win64;C:\Users\亮\AppData\Roaming\npm
9 verbose lifecycle cocalc@1.0.0~install-all: CWD: G:\opensource\cocalc\src
10 silly lifecycle cocalc@1.0.0~install-all: Args: [ '/d /s /c', 'scripts/smc-install-all' ]
11 silly lifecycle cocalc@1.0.0~install-all: Returned: code: 1  signal: null
12 info lifecycle cocalc@1.0.0~install-all: Failed to exec install-all script
13 verbose stack Error: cocalc@1.0.0 install-all: `scripts/smc-install-all`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid cocalc@1.0.0
15 verbose cwd G:\opensource\cocalc\src
16 verbose Windows_NT 6.3.9600
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "install-all"
18 verbose node v8.9.4
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error cocalc@1.0.0 install-all: `scripts/smc-install-all`
22 error Exit status 1
23 error Failed at the cocalc@1.0.0 install-all script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by shinytang6** [comment]
found the err
