### ISSUE TITLE
project startup not robust against SQLite DB issues

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#2766]
during startup, this can happen: `Uncaught exception: SqliteError: database disk image is malformed`

```
2018-03-22T11:06:30.276Z - debug: Uncaught exception: SqliteError: database disk image is malformed
2018-03-22T11:06:30.278Z - debug: SqliteError: database disk image is malformed
    at new BlobStore (/cocalc/src/smc-project/jupyter/jupyter-blobs-sqlite.js:35:16)
    at Object.<anonymous> (/cocalc/src/smc-project/jupyter/jupyter-blobs-sqlite.js:136:24)
    at Object.<anonymous> (/cocalc/src/smc-project/jupyter/jupyter-blobs-sqlite.js:138:4)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    [...]
```

project should still start, though

* is there a command to attempt a fix?
* plan B is to simply delete the database

**Comment by williamstein** [comment]
Definitely do plan B -- just delete it.  The db is only used as a local cache.
