### ISSUE TITLE
Exporting from Jupyter notebooks with a sage kernel to Sage worksheets gives a bad first cell

### ISSUE THREAD

**Issue by kevinywlui** [sagemathinc/cocalc#2981]
1. Start with any Jupyter notebook with a sage kernel.
2. Export to a Sage worksheet using File -> Download as -> Sage worksheet which uses `smc-ipynb2sagews`
3. The first cell will be
```
%auto
# This cell automatically evaluates on startup -- or run it manually if it didn't evaluate.
# Here, it initializes the Jupyter kernel with the specified name and sets it as the default mode for this worksheet.
jupyter_kernel = jupyter("sagemath")  # run "jupyter?" for more information.
%default_mode jupyter_kernel
```
which yields the error
```
Error in lines 1-1
Traceback (most recent call last):
  File "/cocalc/lib/python2.7/site-packages/smc_sagews/sage_server.py", line 1044, in execute
    exec compile(block+'\n', '', 'single', flags=compile_flags) in namespace, locals
  File "", line 1, in <module>
  File "/cocalc/lib/python2.7/site-packages/smc_sagews/sage_jupyter.py", line 32, in __call__
    raise ValueError("You may not run Sage kernels from a Sage worksheet.\nInstead use the sage_select command in a Terminal to\nswitch to a different version of Sage, then restart your project.")
ValueError: You may not run Sage kernels from a Sage worksheet.
Instead use the sage_select command in a Terminal to
switch to a different version of Sage, then restart your project.
```

**Comment by DrXyzzy** [comment]
Function [jupyter.available_kernels()](https://github.com/sagemathinc/cocalc/blob/master/src/smc_sagews/smc_sagews/sage_jupyter.py#L35) in sage server code filters out kernels whose names begin with "sage", because it's expected that sage worksheets will run sagemath programs without the jupyter bridge.

Fix is to modify utility [smc-ipynb2sagews.py](https://github.com/sagemathinc/cocalc/blob/master/src/smc_pyutil/smc_pyutil/ipynb2sagews.py) to not configure the bridge in these cases.

**Comment by williamstein** [comment]
fixed, long ago
