### ISSUE TITLE
cc-in-cc: project stacktrace after restart

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#3164]
I don't know how severe this problem is. Each time I restart my project this stacktrace is in the log. I don't know if it also happens in prod.

```
2018-09-10T15:32:54.018Z - debug: Client.get_hub_socket: there are 1 sockets -- ["6b9bb1b5-98f2-46ec-be57-67e33a2c50c9"]                                                                                                       [125/9869]
2018-09-10T15:32:54.018Z - debug: Client.call(message={"id":"15cfe615-5c9a-4f28-ab4f-2919ad55d14d","query":{"public_paths":[{"id":null,"project_id":"bc6f81b3-25ad-4d58-ae4a-65649fae4fa5","path":null,"last_edited":null,"disabled":null
}]},"changes":true,"multi_response":true,"options":[{"only_changes":true}],"event":"query"}):
2018-09-10T15:32:54.018Z - debug: Client.call(message={"id":"15cfe615-5c9a-4f28-ab4f-2919ad55d14d","query":{"public_paths":[{"id":null,"project_id":"bc6f81b3-25ad-4d58-ae4a-65649fae4fa5","path":null,"last_edited":null,"disabled":null
}]},"changes":true,"multi_response":true,"options":[{"only_changes":true}],"event":"query"}): configure timeout
[object Object]
    at exports.defaults (/home/user/smc/src/smc-util/opts.coffee:130:19)
    at Client.query (/home/user/smc/src/smc-project/client.coffee:640:12)
    at SyncTable._do_initial_read_query (/home/user/smc/src/smc-util/synctable.coffee:556:25)
    at /home/user/smc/src/smc-util/node_modules/async/lib/async.js:718:13
    at async.forEachOf.async.eachOf (/home/user/smc/src/smc-util/node_modules/async/lib/async.js:233:13)
    at _parallel (/home/user/smc/src/smc-util/node_modules/async/lib/async.js:717:9)
    at async.parallel (/home/user/smc/src/smc-util/node_modules/async/lib/async.js:731:9)
    at SyncTable._do_the_query_using_db_standby (/home/user/smc/src/smc-util/synctable.coffee:528:12)
    at SyncTable._reconnect (/home/user/smc/src/smc-util/synctable.coffee:424:19)
    at async.series (/home/user/smc/src/smc-util/synctable.coffee:404:21)
    at /home/user/smc/src/smc-util/node_modules/async/lib/async.js:718:13
    at Immediate.iterate (/home/user/smc/src/smc-util/node_modules/async/lib/async.js:262:13)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
 
2018-09-10T15:32:54.022Z - debug: BUG ****************************************************************************
2018-09-10T15:32:54.022Z - debug: Uncaught exception: Error: misc.defaults -- TypeError: got an unexpected argument 'standby'
2018-09-10T15:32:54.022Z - debug: Error: misc.defaults -- TypeError: got an unexpected argument 'standby'
    at exports.defaults (/home/user/smc/src/smc-util/opts.coffee:132:19)
    at Client.query (/home/user/smc/src/smc-project/client.coffee:640:12)
    at SyncTable._do_initial_read_query (/home/user/smc/src/smc-util/synctable.coffee:556:25)
    at /home/user/smc/src/smc-util/node_modules/async/lib/async.js:718:13
    at async.forEachOf.async.eachOf (/home/user/smc/src/smc-util/node_modules/async/lib/async.js:233:13)
    at _parallel (/home/user/smc/src/smc-util/node_modules/async/lib/async.js:717:9)
    at async.parallel (/home/user/smc/src/smc-util/node_modules/async/lib/async.js:731:9)
    at SyncTable._do_the_query_using_db_standby (/home/user/smc/src/smc-util/synctable.coffee:528:12)
    at SyncTable._reconnect (/home/user/smc/src/smc-util/synctable.coffee:424:19)
    at async.series (/home/user/smc/src/smc-util/synctable.coffee:404:21)
    at /home/user/smc/src/smc-util/node_modules/async/lib/async.js:718:13
    at Immediate.iterate [as _onImmediate] (/home/user/smc/src/smc-util/node_modules/async/lib/async.js:262:13)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
 
2018-09-10T15:32:54.022Z - debug: BUG ****************************************************************************
[object Object]
    at process.<anonymous> (/home/user/smc/src/smc-project/local_hub.coffee:66:15)
    at emitOne (events.js:116:13)
    at process.emit (events.js:211:7)
    at process.emit (/home/user/smc/src/smc-project/node_modules/source-map-support/source-map-support.js:454:21)
    at process._fatalException (bootstrap_node.js:378:26)
 
2018-09-10T15:32:54.120Z - debug: Client.handle_mesg({"id":"15cfe615-5c9a-4f28-ab4f-2919ad55d14d","query":{},"changes":true,"multi_response":true,"options":[{"only_changes":true}],"event":"query"}): calling callback
```

**Comment by haraldschilly** [comment]
Hmm, I see there is `_do_the_query_using_db_standby` in the stacktrace, so, this is likely something which got introduced recently.

**Comment by williamstein** [comment]
Just put in a dummy argument and ignore it in the backend client.  This is very, very serious.

**Comment by williamstein** [comment]
I'll do it, obviously.

**Comment by haraldschilly** [comment]
I made https://github.com/sagemathinc/cocalc/pull/3165 but that's a silly band-aid, at best ...

**Comment by williamstein** [comment]
I already pushed a fix.
