### ISSUE TITLE
In local docker installation - Library is stuck on Loading ...

### ISSUE THREAD

**Issue by dimitar-petrov** [sagemathinc/cocalc#3370]
On create new files for a python project I get the following:

![library-loading](https://user-images.githubusercontent.com/4025446/49140661-8497f900-f2fd-11e8-8942-2e4a46f9a797.png)

Also I am unable to install packages in the project. It is referring to system py2.
Is the project using some virtualenv mechanism?

```
~$ pip install --user arctic
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    from pip import main
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 22, in <module>
    from pip._vendor.requests.packages.urllib3.exceptions import DependencyWarning
  File "/usr/lib/python2.7/dist-packages/pip/_vendor/__init__.py", line 76, in <module>
    vendored("pkg_resources")
  File "/usr/lib/python2.7/dist-packages/pip/_vendor/__init__.py", line 36, in vendored
    __import__(modulename, globals(), locals(), level=0)
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 3088, in <module>
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 3072, in _call_aside
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 3101, in _initialize_master_working_set
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 565, in _build_master
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 558, in __init__
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 614, in add_entry
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 1964, in find_on_path
  File "/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 2026, in distributions_from_metadata
OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/virtualenv-16.1.0.dist-info'
```

**Comment by haraldschilly** [comment]
There is no library on docker. Once [this PR](https://github.com/sagemathinc/cocalc/pull/3359) is in, it won't show up. 

The pip-install error looks strange. I'll move that issue over to the https://github.com/sagemathinc/cocalc-docker/ repo.
