### ISSUE TITLE
create directory with existing filename breaks

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#3521]
1. in your home dir, run `touch foo` to create a normal file.

**Case 1:** in the file search box type in `foo/bar.md` to create that file, which implicitly tries to create a directory named `foo`. Problem: you can't do that. The error is confusing, and this should rather be caught and properly reported to the user.

> Error: command 'smc-new-file' (args=foo/bar.md) exited with nonzero code 1 -- stderr='Traceback (most recent call last): File "/cocalc/bin/smc-new-file", line 12, in <module> sys.exit(main()) File "/cocalc/lib/python2.7/site-packages/smc_pyutil/new_file.py", line 46, in main new_file(x) File "/cocalc/lib/python2.7/site-packages/smc_pyutil/new_file.py", line 29, in new_file open(path, 'w').close() IOError: [Errno 20] Not a directory: 'foo/bar.md' '

**Case 2:** type in `foo/bar/` to create a nested dir structure. Again, you can't do that.

> alertError creating directory 'foo/bar' -- Error: command 'mkdir' (args=-p foo/bar) exited with nonzero code 1 -- stderr='mkdir: cannot create directory ‘foo’: Not a directory '

additionally, a silly red overlay alert-box appears, with the message: `{}`. that shouldn't appear here at all.

---

Expected results:

1. in both cases, tell the user a suitable error message. I'm not sure if it makes sense, but we could caught such attempts to create a with the name of an existing file even before we even send a call to the project.  (i.e. split the path, match against current files in the dir listing  [if the listing exists])

**Comment by williamstein** [comment]
Ah hah!

**Comment by williamstein** [comment]
Yes, still an ugly error message.  It is a meaningful and correct one though, so this is no longer a bug, but an idea about how to make things more friendly.

<img width="1408" alt="image" src="https://github.com/user-attachments/assets/073708f4-1fcc-4bbf-95b6-5cbe74838580">
