### ISSUE TITLE
please install sage package 'p_group_cohomology'

### ISSUE THREAD

**Issue by DrXyzzy** [sagemathinc/cocalc#3610]
Requested by Alexander Rahm.

Note that in sage-8.6:
```
sage: from sage.misc.package import list_packages
sage: pkgs = list_packages(local=True)
sage: pss = sorted(pkgs.keys())
sage: 'p_group_cohomology' in pss
True
```

Ref:
* https://users.fmi.uni-jena.de/cohomology/documentation/
* https://trac.sagemath.org/ticket/26001

**Comment by haraldschilly** [comment]
I've started to look into this. First hurdle is that it also depends on `meataxe`, so, that will be installed as well.

What would be a good snippet of code that depends on p_group_cohomology and can be used to test that it is installed and actually working?

**Comment by haraldschilly** [comment]
Well, I am aware that it was updated, but my notes from some time ago say that it is broken, and here is how it ends up in sage 8.6 after a second try. Did I completely break it, is there a way to make this work?

```
$ ./sage -i p_group_cohomology
[...]
make[1]: Entering directory '/ext/sage/sage-8.6_1804/build/make'
if [ -z "$SAGE_INSTALL_FETCH_ONLY" ]; then \
        cd /ext/sage/sage-8.6_1804/src && source bin/sage-env && \
        sage-logger -p 'time make sage' '/ext/sage/sage-8.6_1804/logs/pkgs/sagelib-8.6.log'; \
fi
[sagelib-8.6] make[2]: Entering directory '/ext/sage/sage-8.6_1804/src'
[sagelib-8.6] cd . && export                                    \
[sagelib-8.6]     SAGE_ROOT=/doesnotexist                               \
[sagelib-8.6]     SAGE_SRC=/doesnotexist                                \
[sagelib-8.6]     SAGE_SRC_ROOT=/doesnotexist                           \
[sagelib-8.6]     SAGE_DOC_SRC=/doesnotexist                            \
[sagelib-8.6]     SAGE_BUILD_DIR=/doesnotexist                          \
[sagelib-8.6]     SAGE_PKGS=/ext/sage/sage-8.6_1804/build/pkgs                \
[sagelib-8.6] && sage-python23 -u setup.py --no-user-cfg build install
[sagelib-8.6] DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
[sagelib-8.6] Discovering Python/Cython source code....
[sagelib-8.6] Discovered Python/Cython sources, time: 0.03 seconds.
[sagelib-8.6] running build
[sagelib-8.6] Generating auto-generated sources
[sagelib-8.6] Building interpreters for fast_callable
[sagelib-8.6] running build_cython
[sagelib-8.6] Enabling Cython debugging support
[sagelib-8.6] Updating Cython code....
[sagelib-8.6] [  1/502] Cythonizing sage/rings/complex_double.pyx
[sagelib-8.6] 
[sagelib-8.6] Error compiling Cython file:
[sagelib-8.6] ------------------------------------------------------------
[sagelib-8.6] ...
[sagelib-8.6] from .real_double cimport RealDoubleElement, double_repr
[sagelib-8.6] from .real_double import RDF
[sagelib-8.6] from sage.rings.integer_ring import ZZ
[sagelib-8.6] 
[sagelib-8.6] IF HAVE_GMPY2:
[sagelib-8.6]     cimport gmpy2
[sagelib-8.6]            ^
[sagelib-8.6] ------------------------------------------------------------
[sagelib-8.6] 
[sagelib-8.6] sage/rings/complex_double.pyx:111:12: 'gmpy2.pxd' not found
[sagelib-8.6] warning: sage/rings/complex_double.pyx:1590:4: Overriding cdef method with def method.
[sagelib-8.6] 
[sagelib-8.6] Error compiling Cython file:
[sagelib-8.6] ------------------------------------------------------------
[sagelib-8.6] ...
[sagelib-8.6] from .real_double import RDF
[sagelib-8.6] from sage.rings.integer_ring import ZZ
[sagelib-8.6] 
[sagelib-8.6] IF HAVE_GMPY2:
[sagelib-8.6]     cimport gmpy2
[sagelib-8.6]     gmpy2.import_gmpy2()
[sagelib-8.6]         ^
[sagelib-8.6] ------------------------------------------------------------
[sagelib-8.6] 
[sagelib-8.6] sage/rings/complex_double.pyx:112:9: cimported module has no attribute 'import_gmpy2'
[sagelib-8.6] 
[sagelib-8.6] Error compiling Cython file:
[sagelib-8.6] ------------------------------------------------------------
[sagelib-8.6] ...
[sagelib-8.6]             return ComplexDoubleElement(x.real, x.imag)
[sagelib-8.6]         elif isinstance(x, complex_number.ComplexNumber):
[sagelib-8.6]             return ComplexDoubleElement(x.real(), x.imag())
[sagelib-8.6]         elif isinstance(x, pari_gen):
[sagelib-8.6]             return pari_to_cdf(x)
[sagelib-8.6]         elif HAVE_GMPY2 and type(x) is gmpy2.mpc:
[sagelib-8.6]                                            ^
[sagelib-8.6] ------------------------------------------------------------
[sagelib-8.6] 
[sagelib-8.6] sage/rings/complex_double.pyx:355:44: cimported module has no attribute 'mpc'
[sagelib-8.6] 
[sagelib-8.6] Error compiling Cython file:
[sagelib-8.6] ------------------------------------------------------------
[sagelib-8.6] ...
[sagelib-8.6]         elif isinstance(x, complex_number.ComplexNumber):
[sagelib-8.6]             return ComplexDoubleElement(x.real(), x.imag())
[sagelib-8.6]         elif isinstance(x, pari_gen):
[sagelib-8.6]             return pari_to_cdf(x)
[sagelib-8.6]         elif HAVE_GMPY2 and type(x) is gmpy2.mpc:
[sagelib-8.6]             return ComplexDoubleElement((<gmpy2.mpc>x).real, (<gmpy2.mpc>x).imag)
[sagelib-8.6]                                          ^
[sagelib-8.6] ------------------------------------------------------------
[sagelib-8.6] 
[sagelib-8.6] sage/rings/complex_double.pyx:356:42: 'mpc' is not a type identifier
[sagelib-8.6] 
[sagelib-8.6] Error compiling Cython file:
[sagelib-8.6] ------------------------------------------------------------
[sagelib-8.6] ...
[sagelib-8.6]         elif isinstance(x, complex_number.ComplexNumber):
[sagelib-8.6]             return ComplexDoubleElement(x.real(), x.imag())
[sagelib-8.6]         elif isinstance(x, pari_gen):
[sagelib-8.6]             return pari_to_cdf(x)
[sagelib-8.6]         elif HAVE_GMPY2 and type(x) is gmpy2.mpc:
[sagelib-8.6]             return ComplexDoubleElement((<gmpy2.mpc>x).real, (<gmpy2.mpc>x).imag)
[sagelib-8.6]                                                               ^
[sagelib-8.6] ------------------------------------------------------------
[sagelib-8.6] 
[sagelib-8.6] sage/rings/complex_double.pyx:356:63: 'mpc' is not a type identifier
[sagelib-8.6] 
[sagelib-8.6] Error compiling Cython file:
[sagelib-8.6] ------------------------------------------------------------
[sagelib-8.6] ...
[sagelib-8.6]             Traceback (most recent call last):
[sagelib-8.6]             ...
[sagelib-8.6]             NotImplementedError: gmpy2 is not installed
[sagelib-8.6]         """
[sagelib-8.6]         IF HAVE_GMPY2:
[sagelib-8.6]             return gmpy2.mpc(self._complex.dat[0], self._complex.dat[1])
[sagelib-8.6]                        ^
[sagelib-8.6] ------------------------------------------------------------
[sagelib-8.6] 
[sagelib-8.6] sage/rings/complex_double.pyx:1122:24: cimported module has no attribute 'mpc'
[sagelib-8.6] Traceback (most recent call last):
[sagelib-8.6]   File "/ext/sage/sage-8.6_1804/local/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 1244, in cythonize_one_helper
[sagelib-8.6]     return cythonize_one(*m)
[sagelib-8.6]   File "/ext/sage/sage-8.6_1804/local/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 1220, in cythonize_one
[sagelib-8.6]     raise CompileError(None, pyx_file)
[sagelib-8.6] CompileError: sage/rings/complex_double.pyx
[sagelib-8.6] [  2/502] Cythonizing sage/arith/functions.pyx
[sagelib-8.6] ************************************************************************
[sagelib-8.6] Traceback (most recent call last):
[sagelib-8.6]   File "setup.py", line 958, in <module>
[sagelib-8.6]     ext_modules = ext_modules)
[sagelib-8.6]   File "/ext/sage/sage-8.6_1804/local/lib/python2.7/distutils/core.py", line 151, in setup
[sagelib-8.6]     dist.run_commands()
[sagelib-8.6]   File "/ext/sage/sage-8.6_1804/local/lib/python2.7/distutils/dist.py", line 953, in run_commands
[sagelib-8.6]     self.run_command(cmd)
[sagelib-8.6]   File "/ext/sage/sage-8.6_1804/local/lib/python2.7/distutils/dist.py", line 972, in run_command
[sagelib-8.6]     cmd_obj.run()
[sagelib-8.6]   File "setup.py", line 857, in run
[sagelib-8.6]     build.run(self)
[sagelib-8.6]   File "/ext/sage/sage-8.6_1804/local/lib/python2.7/distutils/command/build.py", line 127, in run
[sagelib-8.6]     self.run_command(cmd_name)
[sagelib-8.6]   File "/ext/sage/sage-8.6_1804/local/lib/python2.7/distutils/cmd.py", line 326, in run_command
[sagelib-8.6]     self.distribution.run_command(command)
[sagelib-8.6]   File "/ext/sage/sage-8.6_1804/local/lib/python2.7/distutils/dist.py", line 972, in run_command
[sagelib-8.6]     cmd_obj.run()
[sagelib-8.6]   File "setup.py", line 376, in run
[sagelib-8.6]     cache=False,
[sagelib-8.6]   File "/ext/sage/sage-8.6_1804/local/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 1088, in cythonize
[sagelib-8.6]     result.get(99999)  # seconds
[sagelib-8.6]   File "/ext/sage/sage-8.6_1804/local/lib/python2.7/multiprocessing/pool.py", line 572, in get
[sagelib-8.6]     raise self._value
[sagelib-8.6] CompileError: sage/rings/complex_double.pyx
[sagelib-8.6] ************************************************************************
[sagelib-8.6] Error building the Sage library
[sagelib-8.6] ************************************************************************
[sagelib-8.6] Please email sage-devel (http://groups.google.com/group/sage-devel)
[sagelib-8.6] explaining the problem and including the relevant part of the log file
[sagelib-8.6]   /ext/sage/sage-8.6_1804/logs/pkgs/sagelib-8.6.log
[sagelib-8.6] Describe your computer, operating system, etc.
[sagelib-8.6] ************************************************************************
[sagelib-8.6] Makefile:33: recipe for target 'sage' failed
[sagelib-8.6] make[2]: *** [sage] Error 1
[sagelib-8.6] make[2]: Leaving directory '/ext/sage/sage-8.6_1804/src'
[sagelib-8.6] 
[sagelib-8.6] real      0m12.754s
[sagelib-8.6] user      0m10.907s
[sagelib-8.6] sys       0m1.409s
Makefile:1941: recipe for target 'sagelib' failed
make[1]: *** [sagelib] Error 2
make[1]: Leaving directory '/ext/sage/sage-8.6_1804/build/make'

real    0m12.898s
user    0m11.028s
sys     0m1.445s
***************************************************************
Error building Sage.

The following package(s) may have failed to build (not necessarily
during this run of 'make p_group_cohomology'):

* package: cryptominisat-5.0.1
  log file: /ext/sage/sage-8.6_1804/logs/pkgs/cryptominisat-5.0.1.log
  build directory: /ext/sage/sage-8.6_1804/local/var/tmp/sage/build/cryptominisat-5.0.1

* package: cryptominisat
  log file: /ext/sage/sage-8.6_1804/logs/pkgs/cryptominisat.log
  build directory: /ext/sage/sage-8.6_1804/local/var/tmp/sage/build/cryptominisat

* package: database_gap
  log file: /ext/sage/sage-8.6_1804/logs/pkgs/database_gap.log
  build directory: /ext/sage/sage-8.6_1804/local/var/tmp/sage/build/database_gap

* package: database_pari
  log file: /ext/sage/sage-8.6_1804/logs/pkgs/database_pari.log
  build directory: /ext/sage/sage-8.6_1804/local/var/tmp/sage/build/database_pari

* package: p_group_cohomology
  log file: /ext/sage/sage-8.6_1804/logs/pkgs/p_group_cohomology.log
  build directory: /ext/sage/sage-8.6_1804/local/var/tmp/sage/build/p_group_cohomology

* package: phc
  log file: /ext/sage/sage-8.6_1804/logs/pkgs/phc.log
  build directory: /ext/sage/sage-8.6_1804/local/var/tmp/sage/build/phc

* package: qepcad
  log file: /ext/sage/sage-8.6_1804/logs/pkgs/qepcad.log
  build directory: /ext/sage/sage-8.6_1804/local/var/tmp/sage/build/qepcad

* package: sagelib-8.6
  log file: /ext/sage/sage-8.6_1804/logs/pkgs/sagelib-8.6.log
  build directory: /ext/sage/sage-8.6_1804/local/var/tmp/sage/build/sagelib-8.6

The build directory may contain configuration files and other potentially
helpful information. WARNING: if you now run 'make' again, the build
directory will, by default, be deleted. Set the environment variable
SAGE_KEEP_BUILT_SPKGS to 'yes' to prevent this.

Makefile:31: recipe for target 'p_group_cohomology' failed
make: *** [p_group_cohomology] Error 1

**Comment by DrXyzzy** [comment]
> What would be a good snippet of code that depends on p_group_cohomology and can be used to test that it is installed and actually working?

I was working with the start of the [pGroupCohomology doc](https://users.fmi.uni-jena.de/cohomology/documentation/pGroupCohomology.html), e.g.:
```
from pGroupCohomology import CohomologyRing
CohomologyRing.doctest_setup()       # reset, block web access, use temporary workspace
H0 = CohomologyRing(8,3)
```

**Comment by simon-king-jena** [comment]
Hi!

Samuel Lelièvre made me aware of this discussion (I am author of p_group_cohomology).

Harald, you wrote that your "notes from some time ago say that it is broken". The p_group_cohomology package depends on stuff in the Sage library, so, it has happened from time to time that a backward incompatible change in the Sage library broke the cohomology package. But due to ticket 26001, which was merged in sagemath-8.6, it is supposed to work.

However, from the log you attached, it seems to me that you are missing an important dependency for p_group_cohomology: Sage! Your log says: 
```
[sagelib-8.6] sage/rings/complex_double.pyx:356:63: 'mpc' is not a type identifier
[sagelib-8.6] 
[sagelib-8.6] Error compiling Cython file:
[sagelib-8.6] ------------------------------------------------------------
[sagelib-8.6] ...
[sagelib-8.6]             Traceback (most recent call last):
[sagelib-8.6]             ...
[sagelib-8.6]             NotImplementedError: gmpy2 is not installed
[sagelib-8.6]         """
[sagelib-8.6]         IF HAVE_GMPY2:
[sagelib-8.6]             return gmpy2.mpc(self._complex.dat[0], self._complex.dat[1])

```
So, sagelib is broken, hence, you do not have a working Sage installation, but p_group_cohomology depends on sagelib.

Note to people who have used p_group_cohomology before: Previously, it was possible to use it on groups defined in the GAP pexpect interface. Now, I have switched to using libgap. See the examples in the [documentation](https://users.fmi.uni-jena.de/cohomology/documentation/).

Best regards,
Simon

**Comment by simon-king-jena** [comment]
> > What would be a good snippet of code that depends on p_group_cohomology and can be used to test that it is installed and actually working?
> 
> I was working with the start of the [pGroupCohomology doc](https://users.fmi.uni-jena.de/cohomology/documentation/pGroupCohomology.html), e.g.:
> 
> ```
> from pGroupCohomology import CohomologyRing
> CohomologyRing.doctest_setup()       # reset, block web access, use temporary workspace
> H0 = CohomologyRing(8,3)
> ```

Actually one would usually ommit "CohomologyRing.doctest_setup()" unless one writes a doctest. Reason of this method: It empties the cache, sets up a temporary workspace (otherwise the test would depend on the state of the user's workspace), and blocks internet access (which is needed for tests that are executed during package installation, in which case Sage isn't happy with internet access).

So, it depends on the purpose of the code snipped.

Best regards,
Simon

**Comment by haraldschilly** [comment]
bummer. I fear I'm not qualified to install that package. I was able to fix that library issue and installing it ends with

```
[p_group_cohomology-3.1] Successfully built pGroupCohomology                                                                  
[p_group_cohomology-3.1] Installing collected packages: pGroupCohomology                                                      
[p_group_cohomology-3.1]                                                                                                      
[p_group_cohomology-3.1] Successfully installed pGroupCohomology-3.1                                                          
[p_group_cohomology-3.1] Cleaning up...                                                                                       
[p_group_cohomology-3.1] Removed build tracker '/tmp/pip-req-tracker-pQVJu7'                                                  
[p_group_cohomology-3.1]                                                                                                      
[p_group_cohomology-3.1] real   12m31.627s                                                                                    
[p_group_cohomology-3.1] user   11m31.577s                                                                                    
[p_group_cohomology-3.1] sys    0m11.726s                                                                                     
[p_group_cohomology-3.1] Copying package files from temporary location /ext/sage/sage-8.6_1804/local/var/tmp/sage/build/p_grou
p_cohomology-3.1/inst to /ext/sage/sage-8.6_1804/local                                                                        
[p_group_cohomology-3.1] Successfully installed p_group_cohomology-3.1                                                        
[p_group_cohomology-3.1] Deleting temporary build directory                                                                   
[p_group_cohomology-3.1] /ext/sage/sage-8.6_1804/local/var/tmp/sage/build/p_group_cohomology-3.1                              
[p_group_cohomology-3.1] Finished installing p_group_cohomology-3.1.spkg                                                      
make[1]: Leaving directory '/ext/sage/sage-8.6_1804/build/make'                                                               
                                                                                                                              
real    13m49.938s                                                                                                            
user    12m20.974s                                                                                                            
sys     0m24.169s                                                                                                             
Sage build/upgrade complete!                                                                                                  
```

… but please keep your campaign bottles closed. there must be something else that I have to install or move around. the snippet above errors with a complaint about a missing: `/ext/sage/sage-8.6_1804/local/share/sage/ext/gap/modular_cohomology/GapMaxels.g`

I found it here, though:

```
$ find /ext/sage/sage-8.6_1804/ -name GapMaxels.g
/ext/sage/sage-8.6_1804/local/lib/python2.7/site-packages/ext/sage/sage-8.6_1804/local/share/sage/ext/gap/modular_cohomology/GapMaxels.g
```

upstream: https://trac.sagemath.org/ticket/18514?cversion=0&cnum_hist=182#comment:284

In the sage env, where I installed it, that's `SAGE_SHARE`

```
(sage-sh) salvus@3dbcc2185803:sage-8.6_1804$ echo $SAGE_SHARE
/ext/sage/sage-8.6_1804/local/share
```

![screenshot from 2019-02-21 17-58-56](https://user-images.githubusercontent.com/207405/53186976-6000a400-3602-11e9-9f81-98508edc7148.png)

**Comment by simon-king-jena** [comment]
Hi Harald,

> [p_group_cohomology-3.1] Successfully installed p_group_cohomology-3.1                                                        

Hooray!

> … but please keep your campaign bottles closed. there must be something else that I have to install or move around. the snippet above errors with a complaint about a missing: `/ext/sage/sage-8.6_1804/local/share/sage/ext/gap/modular_cohomology/GapMaxels.g`
> 
> I found it here, though:
> 
> ```
> $ find /ext/sage/sage-8.6_1804/ -name GapMaxels.g
> /ext/sage/sage-8.6_1804/local/lib/python2.7/site-packages/ext/sage/sage-8.6_1804/local/share/sage/ext/gap/modular_cohomology/GapMaxels.g
> ```
> 
> upstream: https://trac.sagemath.org/ticket/18514?cversion=0&cnum_hist=182#comment:284

That's likely a different issue. If I recall correctly, the discussion on the ticket was a problem of non-published development versions of p_group_cohomology: In different development versions I used different file locations.

`/ext/sage/sage-8.6_1804/local/lib/python2.7/site-packages/ext/sage/sage-8.6_1804/local/share/sage/ext/gap/` certainly is an interesting path. It looks as if `$SAGE_SHARE` was appended to another path.

Here is how the helper files get installed. p_group_cohomology's `setup.py` says:
```
  data_files=[(os.path.join(SAGE_SHARE,"sage","ext","gap","modular_cohomology"),
              [os.path.join("pGroupCohomology","GapMaxels.g"),
               os.path.join("pGroupCohomology","GapMB.g"),
               os.path.join("pGroupCohomology","GapSgs.g")]),
              (os.path.join(SAGE_SHARE,'singular','LIB'),
               [os.path.join("pGroupCohomology","dickson.lib")])],
```
I have absolutely no idea how this could make the files end up in the wrong location.
Best regards,
Simon

**Comment by simon-king-jena** [comment]
Harald,
has the problem been solved? The GAP helper files are supposed to be in `SAGE_SHARE/sage/ext/gap/modular_cohomology/`, and I don't see how the package's `setup.py` could possibly get that location wrong.

`setup.py` does the following import: `from sage.env import sage_include_directories, SAGE_SHARE`. Is it perhaps the case that due to some very odd configuration the value of `SAGE_SHARE` during package installation is different than during a regular Sage session? The folder in which you eventually found the helper files seems strange.

Best regards,
Simon

**Comment by haraldschilly** [comment]
well, this is still open. I tried to fix/recompile this the last time, thought I had a bit of progress, but with the latest version on cocalc it's still broken.

```
~$ sage
┌────────────────────────────────────────────────────────────────────┐
│ SageMath version 8.7, Release Date: 2019-03-23                     │
│ Create a "Sage Worksheet" file for the notebook interface.         │
│ Enhanced for CoCalc.                                               │
│ Using Python 2.7.15. Type "help()" for help.                       │
└────────────────────────────────────────────────────────────────────┘
sage: from pGroupCohomology import CohomologyRing
....: H0 = CohomologyRing(8,3)
....: H0
....: 
WARNING: Files on disk have been moved or are not writeable.
> Will try to recover later.
8gp3: Files on disk have been moved - trying to get things right
p002.zzz: No such file or directory
```

**Comment by simon-king-jena** [comment]
Hi Harald,

seriously? The error message looks as if path names are messed up. The
file "p002.zzz" is supposed to be available in $DOTSAGE/meataxe. If it
isn't there, then it should automatically be created there. And the file
creation should be possible, since the user is supposed to have write
access to $DOTSAGE.

Is DOTSAGE treated in strange ways, in cocalc?

Can you tell me the value of DOTSAGE when the error occurs?

In any case, the problem comes from meataxe, not from
p_group_cohomology. What does the test suite say? I.e. "sage -t
--optional=sage,meataxe" or whatever the syntax is for running optional
doctests.

Best regards,
Simon

Am 06.05.19 um 14:19 schrieb Harald Schilly:

**Comment by haraldschilly** [comment]
well, just to answer briefly, I'm not aware of any setup regarding DOTSAGE. When I run it in a project, I can only see that it isn't set.

```
~$ echo $DOTSAGE

~$ sage
┌────────────────────────────────────────────────────────────────────┐
│ SageMath version 8.7, Release Date: 2019-03-23                     │
│ Create a "Sage Worksheet" file for the notebook interface.         │
│ Enhanced for CoCalc.                                               │
│ Using Python 2.7.15. Type "help()" for help.                       │
└────────────────────────────────────────────────────────────────────┘
sage: import os
sage: os.environ['DOTSAGE']
[...]
KeyError: 'DOTSAGE'
```

**Comment by simon-king-jena** [comment]
Hi Harald,

sorry, I had a typo in my post. It isn't DOTSAGE, but DOT_SAGE.

For example:

        sage: DOT_SAGE
        '/home/king/.sage/'
        sage: tmp_dir()
        '/home/king/.sage/temp/klap/6934/dir_tcud_J/'

Best regards,
Simon

Am 06.05.19 um 18:07 schrieb Harald Schilly:

**Comment by haraldschilly** [comment]
good news, once 8.9 is rolled out on cocalc, this will work. the first time around it showed me some warnings that files are missing / readonly, ... but then it recreated the files and returned some result. great!

therefore I'm closing this. 8.9 it is! :tada:
