### ISSUE TITLE
mathjax: `Cannot read property 'Event' of undefined`

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#3637]
wasn't there recently a small fix by @williamstein about event being undefined in mathjax? there are more like that. Not much info available, though …

---

chrome: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36`

smc_git_rev: 80802948baca42ff78fbbe31a86a8f8d41ee028b

Date: 2019-02-27 02:32:13.608820

`Cannot read property 'Event' of undefined`

```
TypeError: Cannot read property 'Event' of undefined
    at Object.Startup (https://cocalc.com/static/mathjax-2.7.4/jax/output/SVG/jax.js?V=2.7.4:19:2478)
    at Function.execute (https://cocalc.com/static/mathjax-2.7.4/MathJax.js:19:3242)
    at cb (https://cocalc.com/static/mathjax-2.7.4/MathJax.js:19:2819)
    at Object.Process (https://cocalc.com/static/mathjax-2.7.4/MathJax.js:19:8703)
    at Object.call (https://cocalc.com/static/mathjax-2.7.4/MathJax.js:19:8960)
    at Function.WAITEXECUTE (https://cocalc.com/static/mathjax-2.7.4/MathJax.js:19:6188)
    at cb (https://cocalc.com/static/mathjax-2.7.4/MathJax.js:19:2819)
    at Object.Process (https://cocalc.com/static/mathjax-2.7.4/MathJax.js:19:8703)
    at Object.call (https://cocalc.com/static/mathjax-2.7.4/MathJax.js:19:8960)
    at Function.WAITEXECUTE (https://cocalc.com/static/mathjax-2.7.4/MathJax.js:19:6188)
```

**Comment by williamstein** [comment]
I have no clue about this.
