### ISSUE TITLE
ipynb→pdf broken for SVG plots

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#3707]
tl;dr: exporting an ipynb file with SVG requires inkscape conversion, but somehow that's broken. I don't know if this is specific to cocalc's jupyter, somehow the python setup on cocalc in prod, or a bug in nbconvert.

Create a Python3 notebook with

```
import matplotlib.pyplot as plt
import numpy as np

%config InlineBackend.figure_formats = ['svg']

plt.plot((np.random.rand(1000) - .5).cumsum())
```

and the SVG plot shows up. good.

Then convert to PDF via nbconvert. It fails like that:

```
~$ jupyter-nbconvert --to pdf plot.ipynb 
[NbConvertApp] Converting notebook plot.ipynb to pdf
Failed to get connection
** (inkscape:2562): CRITICAL **: 08:48:54.812: dbus_g_proxy_new_for_name: assertion 'connection != NULL' failed

** (inkscape:2562): CRITICAL **: 08:48:54.812: dbus_g_proxy_call: assertion 'DBUS_IS_G_PROXY (proxy)' failed

** (inkscape:2562): CRITICAL **: 08:48:54.812: dbus_g_connection_register_g_object: assertion 'connection != NULL' failed
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-nbconvert", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/user/.local/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 337, in start
    self.convert_notebooks()
  File "/home/user/.local/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 507, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "/home/user/.local/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 478, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
  File "/home/user/.local/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 407, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "/home/user/.local/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 178, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/home/user/.local/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 196, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "/home/user/.local/lib/python3.6/site-packages/nbconvert/exporters/pdf.py", line 158, in from_notebook_node
    nb, resources=resources, **kw
  File "/home/user/.local/lib/python3.6/site-packages/nbconvert/exporters/latex.py", line 84, in from_notebook_node
    return super(LatexExporter, self).from_notebook_node(nb, resources, **kw)
  File "/home/user/.local/lib/python3.6/site-packages/nbconvert/exporters/templateexporter.py", line 300, in from_notebook_node
    nb_copy, resources = super(TemplateExporter, self).from_notebook_node(nb, resources, **kw)
  File "/home/user/.local/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 138, in from_notebook_node
    nb_copy, resources = self._preprocess(nb_copy, resources)
  File "/home/user/.local/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 315, in _preprocess
    nbc, resc = preprocessor(nbc, resc)
  File "/home/user/.local/lib/python3.6/site-packages/nbconvert/preprocessors/base.py", line 47, in __call__
    return self.preprocess(nb, resources)
  File "/home/user/.local/lib/python3.6/site-packages/nbconvert/preprocessors/base.py", line 69, in preprocess
    nb.cells[index], resources = self.preprocess_cell(cell, resources, index)
  File "/home/user/.local/lib/python3.6/site-packages/nbconvert/preprocessors/extractoutput.py", line 92, in preprocess_cell
    data = json.dumps(data)
  File "/usr/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'bytes' is not JSON serializable
```

The above happens with the most recent 5.4.1  version, 5.4.0 is also broken.

The notebook itself looks like that:

```
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "data": {
      "text/plain": [
       "[<matplotlib.lines.Line2D at 0x7fbfe4872668>]"
      ]
     },
     "execution_count": 5,
     "metadata": {
     },
     "output_type": "execute_result"
    },
    {
     "data": {
      "image/svg+xml": "<?xml version=\"1.0\" encoding=\"utf-8\" standalone=\"no\"?>\n<!DOCTYPE svg PUBLIC \"-//W3C//DTD SVG 1.1//EN\"\n  \"http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd\">\n<!-- Created with matplotlib (http://matplotlib.org/) -->\n<svg height=\"252pt\" version=\"1.1\" viewBox=\"0 0 374 252\" width=\"374pt\" xmlns=\"http://www.w3.org/2000/svg\" 

[...]

\" style=\"fill:none;stroke:#000000;stroke-linecap:square;stroke-linejoin:miter;stroke-width:0.8;\"/>\n   </g>\n  </g>\n </g>\n <defs>\n  <clipPath id=\"pb02230494b\">\n   <rect height=\"217.44\" width=\"334.8\" x=\"28.942188\" y=\"10.7\"/>\n  </clipPath>\n </defs>\n</svg>\n"
     },
     "execution_count": 5,
     "metadata": {
     },
     "output_type": "execute_result"
    }
   ],
   "source": [
    "plt.plot((np.random.rand(1000) - .5).cumsum())"
   ]
  },
```

**Comment by williamstein** [comment]
Even if nbconvert can't fix this, we could do some extra strep where we convert all the svg's to some other nbconvert friendly format.     That would likely be pretty straightforward, given that we can assume so much about our environment (e.g, that imagemagick is there).

**Comment by sdaitzman** [comment]
Replicated this bug. Any luck fixing it or working around it?

**Comment by williamstein** [comment]
Via classic nbconvert this happens:

<img width="1221" alt="image" src="https://github.com/user-attachments/assets/919b736c-4399-44c4-a457-eda8ca340415">

Our default export to PDF, which I think I wrote from scratch using chromium and react works perfectly and is very fast:

<img width="1179" alt="image" src="https://github.com/user-attachments/assets/7d430baf-eaba-4ab4-a5fc-87abd97b4c56">

Jupyterlab nbconvert via cocalc has this result:

<img width="1123" alt="image" src="https://github.com/user-attachments/assets/8b0851d5-2542-4509-a239-bc69c2dd65ed">

Jupyterlab's own pdf export works well (literally using jupyterlab):

<img width="1150" alt="image" src="https://github.com/user-attachments/assets/6d86bca7-160b-44c6-962b-7daef9218c66">

Jupyterlab's builting Print does NOT work:

<img width="580" alt="image" src="https://github.com/user-attachments/assets/74f27bab-42ab-4d67-9aa9-0c53b79aef16">

I'm closing this since I wrote an export to PDF that works very well and it's at the top of our menu, and I'm not going to change nbconvert...
