### ISSUE TITLE
pip install virtualization

### ISSUE THREAD

**Issue by edgarcosta** [sagemathinc/cocalc#4032]
Some pip installs fail due to what I assume is a virtualization of the pip environment.

If I try to install a package using git some files can't be found:

```
~$ sage -pip install git+https://github.com/jwbober/conrey-dirichlet-characters.git@master#egg=dirichlet_conrey --user --version
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting dirichlet_conrey from git+https://github.com/jwbober/conrey-dirichlet-characters.git@master#egg=dirichlet_conrey
  Cloning https://github.com/jwbober/conrey-dirichlet-characters.git (to revision master) to /tmp/pip-install-V60L3r/dirichlet-conrey
  Running command git clone -q https://github.com/jwbober/conrey-dirichlet-characters.git /tmp/pip-install-V60L3r/dirichlet-conrey
  WARNING: Generating metadata for package dirichlet-conrey produced metadata for project name dirichletconrey. Fix your #egg=dirichlet-conrey fragments.
Requirement already satisfied (use --upgrade to upgrade): dirichletconrey from git+https://github.com/jwbober/conrey-dirichlet-characters.git@master#egg=dirichlet_conrey in ./.local/lib/python2.7/site-packages
Building wheels for collected packages: dirichletconrey, dirichletconrey
  Building wheel for dirichletconrey (setup.py) ... done
  Stored in directory: /tmp/pip-ephem-wheel-cache-JC2wxz/wheels/a5/e1/d4/3e9f1ca17ad49397c43e406ac3d11f9844a6f4789dc153a6ad
  Building wheel for dirichletconrey (setup.py) ... error
  ERROR: Complete output from command /ext/sage/sage-8.8_1804/local/bin/python2 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-V60L3r/dirichletconrey/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-B5BpBm --python-tag cp27:
  ERROR: Traceback (most recent call last):
    File "<string>", line 1, in <module>
  IOError: [Errno 2] No such file or directory: '/tmp/pip-install-V60L3r/dirichletconrey/setup.py'
  ----------------------------------------
  ERROR: Failed building wheel for dirichletconrey
  Running setup.py clean for dirichletconrey
  ERROR: Complete output from command /ext/sage/sage-8.8_1804/local/bin/python2 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-V60L3r/dirichletconrey/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all:
  ERROR: Traceback (most recent call last):
    File "<string>", line 1, in <module>
  IOError: [Errno 2] No such file or directory: '/tmp/pip-install-V60L3r/dirichletconrey/setup.py'
  ----------------------------------------
  ERROR: Failed cleaning build dir for dirichletconrey
Successfully built dirichletconrey
Failed to build dirichletconrey
WARNING: You are using pip version 19.1.1, however version 19.2.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```
while if I clone and then install, everything works fine:
```
~$ git clone https://github.com/jwbober/conrey-dirichlet-characters.gitCloning into 'conrey-dirichlet-characters'...
remote: Enumerating objects: 129, done.
remote: Total 129 (delta 0), reused 0 (delta 0), pack-reused 129
Receiving objects: 100% (129/129), 71.74 KiB | 5.52 MiB/s, done.
Resolving deltas: 100% (75/75), done.
~$ sage -pip install conrey-dirichlet-characters/ --user --versionDEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Processing ./conrey-dirichlet-characters
Building wheels for collected packages: DirichletConrey
  Building wheel for DirichletConrey (setup.py) ... done
  Stored in directory: /home/user/.cache/pip/wheels/04/0f/1f/25208085f1d735ac920a71ac6f107e98df4577f4ec178f061c
Successfully built DirichletConrey
Installing collected packages: DirichletConrey
  Found existing installation: DirichletConrey 0.111
    Uninstalling DirichletConrey-0.111:
      Successfully uninstalled DirichletConrey-0.111
Successfully installed DirichletConrey-0.111
WARNING: You are using pip version 19.1.1, however version 19.2.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by haraldschilly** [comment]
well, I don't know what this is or what we can do. maybe this is a Sage upstream issue?

**Comment by williamstein** [comment]
The github repo you are pulling from has directions.  They are broken since `load` is a function, not a command, but it's easy to work around.  I made a PR to update them, and included a working-on-cocalc example:

https://github.com/jwbober/conrey-dirichlet-characters/pull/4/files

**Comment by edgarcosta** [comment]
@williamstein thanks!!!
