### ISSUE TITLE
build error for development

### ISSUE THREAD

**Issue by aaron8tang** [sagemathinc/cocalc#4389]
when i build following the instruction in README.md
npm run install-all
it failed.

Thanks.

-----------------------------------------------------------------

environment:
Ubuntu 18.04.1 LTS
node -v v12.16.0
node-gyp -v v5.0.5
python 3.6.7

-----------------------------------------------------------------

part of error log:

/home/aaron8tang/.cache/node-gyp/12.16.0/include/node/v8.h:3499:22: note: declared here
                 bool Set(Local<Value> key, Local<Value> value));
                      ^
/home/aaron8tang/.cache/node-gyp/12.16.0/include/node/v8config.h:328:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/posix.cc: At global scope:
../src/posix.cc:675:11: error: variable or field ‘init’ declared void
 void init(Handle<Object> exports) {
           ^~~~~~
../src/posix.cc:675:11: error: ‘Handle’ was not declared in this scope
../src/posix.cc:675:11: note: suggested alternative: ‘rand_r’
 void init(Handle<Object> exports) {
           ^~~~~~
           rand_r
../src/posix.cc:675:24: error: expected primary-expression before ‘>’ token
 void init(Handle<Object> exports) {
                        ^
../src/posix.cc:675:26: error: ‘exports’ was not declared in this scope
 void init(Handle<Object> exports) {
                          ^~~~~~~
In file included from ../../nan/nan.h:51:0,
                 from ../src/posix.cc:1:
../src/posix.cc:709:20: error: ‘init’ was not declared in this scope
 NODE_MODULE(posix, init);
                    ^
/home/aaron8tang/.cache/node-gyp/12.16.0/include/node/node.h:601:36: note: in definition of macro ‘NODE_MODULE_X’
       (node::addon_register_func) (regfunc),                          \
                                    ^~~~~~~
../src/posix.cc:709:1: note: in expansion of macro ‘NODE_MODULE’
 NODE_MODULE(posix, init);
 ^~~~~~~~~~~
../src/posix.cc:709:20: note: suggested alternative: ‘int’
 NODE_MODULE(posix, init);
                    ^
/home/aaron8tang/.cache/node-gyp/12.16.0/include/node/node.h:601:36: note: in definition of macro ‘NODE_MODULE_X’
       (node::addon_register_func) (regfunc),                          \
                                    ^~~~~~~
../src/posix.cc:709:1: note: in expansion of macro ‘NODE_MODULE’
 NODE_MODULE(posix, init);
 ^~~~~~~~~~~
posix.target.mk:111: recipe for target 'Release/obj.target/posix/src/posix.o' failed
make: *** [Release/obj.target/posix/src/posix.o] Error 1
make: leave directory“/home/aaron8tang/projects/cocalc/src/smc-project/node_modules/posix/build”
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:321:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 4.15.0-34-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/aaron8tang/projects/cocalc/src/smc-project/node_modules/posix
gyp ERR! node -v v12.16.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! posix@4.1.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the posix@4.1.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/aaron8tang/.npm/_logs/2020-02-17T15_45_53_085Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cocalc@1.0.0 install-all: `scripts/smc-install-all`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cocalc@1.0.0 install-all script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/aaron8tang/.npm/_logs/2020-02-17T15_45_53_121Z-debug.log

**Comment by williamstein** [comment]
What happens if you use the version of Node that we are using (in cocalc), which is:
```
~/cocalc/src/smc-webapp/site-licenses/admin$ node -v
v10.18.1
```

**Comment by aaron8tang** [comment]
> What happens if you use the version of Node that we are using (in cocalc), which is:
> 
> ```
> ~/cocalc/src/smc-webapp/site-licenses/admin$ node -v
> v10.18.1
> ```

Yes, it built successfully, thanks. But failed to pass the test:

aaron8tang@dasuanpan:~/projects/cocalc/src$ npm test

> cocalc@1.0.0 test /home/aaron8tang/projects/cocalc/src
> export SMC_TEST=true&& cd smc-util && npm test && cd ../smc-util-node && npm test && cd ../smc-hub && npm test && cd ../smc-webapp && npm test && cd ../smc-project && npm test


> smc-util@1.0.0 test /home/aaron8tang/projects/cocalc/src/smc-util
> export NODE_ENV=mocha-test && SMC_TEST=true node_modules/.bin/mocha --reporter ${REPORTER:-progress} test/*.coffee; cd test && npx jest

Error: Cannot find module 'smc-webapp/project/websocket/synctable'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/aaron8tang/projects/cocalc/src/smc-util/client.coffee:43:26)
    at Object.<anonymous> (/home/aaron8tang/projects/cocalc/src/smc-util/client.coffee:3171:4)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.loadFile (/home/aaron8tang/projects/cocalc/src/smc-util/node_modules/coffeescript/lib/coffeescript/register.js:18:19)
    at Module.load (/home/aaron8tang/projects/cocalc/src/smc-util/node_modules/coffeescript/lib/coffeescript/register.js:53:36)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/aaron8tang/projects/cocalc/src/smc-util/test/client.coffee:16:12)
    at Object.<anonymous> (/home/aaron8tang/projects/cocalc/src/smc-util/test/client.coffee:49:4)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.loadFile (/home/aaron8tang/projects/cocalc/src/smc-util/node_modules/coffeescript/lib/coffeescript/register.js:18:19)
    at Module.load (/home/aaron8tang/projects/cocalc/src/smc-util/node_modules/coffeescript/lib/coffeescript/register.js:53:36)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at /home/aaron8tang/projects/cocalc/src/smc-util/node_modules/mocha/lib/mocha.js:334:36
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/home/aaron8tang/projects/cocalc/src/smc-util/node_modules/mocha/lib/mocha.js:331:14)
    at Mocha.run (/home/aaron8tang/projects/cocalc/src/smc-util/node_modules/mocha/lib/mocha.js:809:10)
    at Object.exports.singleRun (/home/aaron8tang/projects/cocalc/src/smc-util/node_modules/mocha/lib/cli/run-helpers.js:108:16)
    at exports.runMocha (/home/aaron8tang/projects/cocalc/src/smc-util/node_modules/mocha/lib/cli/run-helpers.js:142:13)
    at Object.exports.handler.argv [as handler] (/home/aaron8tang/projects/cocalc/src/smc-util/node_modules/mocha/lib/cli/run.js:292:3)
    at Object.runCommand (/home/aaron8tang/projects/cocalc/src/smc-util/node_modules/yargs/lib/command.js:242:26)
    at Object.parseArgs [as _parseArgs] (/home/aaron8tang/projects/cocalc/src/smc-util/node_modules/yargs/yargs.js:1087:28)
    at Object.parse (/home/aaron8tang/projects/cocalc/src/smc-util/node_modules/yargs/yargs.js:566:25)
    at Object.exports.main (/home/aaron8tang/projects/cocalc/src/smc-util/node_modules/mocha/lib/cli/cli.js:68:6)
    at Object.<anonymous> (/home/aaron8tang/projects/cocalc/src/smc-util/node_modules/mocha/bin/mocha:164:29)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
 PASS  ./misc2.test.ts (5.234s)
  path_split
    ✓ full path (3ms)
    ✓ filename (1ms)
    ✓ dirname
    ✓ abspath
    ✓ ROOT
  contains_url
    ✓ normal html is fine
    ✓ detects URLs (1ms)

Test Suites: 1 passed, 1 total
Tests:       7 passed, 7 total
Snapshots:   0 total
Time:        5.264s, estimated 6s
Ran all test suites.

> smc-util-node@1.0.0 test /home/aaron8tang/projects/cocalc/src/smc-util-node
> SMC_TEST=true node_modules/.bin/mocha --reporter ${REPORTER:-progress} test/*.coffee

Error: Cannot find module 'smc-util/misc'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/aaron8tang/projects/cocalc/src/smc-util-node/test/misc_node-test.coffee:8:10)
    at Object.<anonymous> (/home/aaron8tang/projects/cocalc/src/smc-util-node/test/misc_node-test.coffee:268:4)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.loadFile (/home/aaron8tang/projects/cocalc/src/smc-util-node/node_modules/coffeescript/lib/coffeescript/register.js:18:19)
    at Module.load (/home/aaron8tang/projects/cocalc/src/smc-util-node/node_modules/coffeescript/lib/coffeescript/register.js:53:36)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at /home/aaron8tang/projects/cocalc/src/smc-util-node/node_modules/mocha/lib/mocha.js:334:36
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/home/aaron8tang/projects/cocalc/src/smc-util-node/node_modules/mocha/lib/mocha.js:331:14)
    at Mocha.run (/home/aaron8tang/projects/cocalc/src/smc-util-node/node_modules/mocha/lib/mocha.js:809:10)
    at Object.exports.singleRun (/home/aaron8tang/projects/cocalc/src/smc-util-node/node_modules/mocha/lib/cli/run-helpers.js:108:16)
    at exports.runMocha (/home/aaron8tang/projects/cocalc/src/smc-util-node/node_modules/mocha/lib/cli/run-helpers.js:142:13)
    at Object.exports.handler.argv [as handler] (/home/aaron8tang/projects/cocalc/src/smc-util-node/node_modules/mocha/lib/cli/run.js:292:3)
    at Object.runCommand (/home/aaron8tang/projects/cocalc/src/smc-util-node/node_modules/yargs/lib/command.js:242:26)
    at Object.parseArgs [as _parseArgs] (/home/aaron8tang/projects/cocalc/src/smc-util-node/node_modules/yargs/yargs.js:1087:28)
    at Object.parse (/home/aaron8tang/projects/cocalc/src/smc-util-node/node_modules/yargs/yargs.js:566:25)
    at Object.exports.main (/home/aaron8tang/projects/cocalc/src/smc-util-node/node_modules/mocha/lib/cli/cli.js:68:6)
    at Object.<anonymous> (/home/aaron8tang/projects/cocalc/src/smc-util-node/node_modules/mocha/bin/mocha:164:29)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
npm ERR! Test failed.  See above for more details.
npm ERR! Test failed.  See above for more details.

**Comment by aaron8tang** [comment]
> What happens if you use the version of Node that we are using (in cocalc), which is:
> 
> ```
> ~/cocalc/src/smc-webapp/site-licenses/admin$ node -v
> v10.18.1
> ```

@williamstein Could you please tell me the version of PostgreSQL you are using? Thanks, William.

**Comment by williamstein** [comment]
```
~/cocalc/src/smc-webapp/jupyter$ psql --version
psql (PostgreSQL) 10.12 (Ubuntu 10.12-1.pgdg18.04+1)
```
