### ISSUE TITLE
sage-9.0: cannot save 3d graphics to image

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#4433]
1. Use `sage_select 9.0` on the command line.
2. Create a Sage worksheet.
3. Type `sphere().save('a.png')`.
4. See a stacktrace:
```
Traceback (most recent call last):
  File "/cocalc/lib/python2.7/site-packages/smc_sagews/sage_server.py", line 1234, in execute
    flags=compile_flags), namespace, locals)
  File "", line 1, in <module>
  File "sage/plot/plot3d/base.pyx", line 1637, in sage.plot.plot3d.base.Graphics3d.save (build/cythonized/sage/plot/plot3d/base.c:21661)
    self.save_image(filename, **kwds)
  File "sage/plot/plot3d/base.pyx", line 1566, in sage.plot.plot3d.base.Graphics3d.save_image (build/cythonized/sage/plot/plot3d/base.c:21219)
    self._save_image_png(filename, **kwds)
  File "sage/plot/plot3d/base.pyx", line 1528, in sage.plot.plot3d.base.Graphics3d._save_image_png (build/cythonized/sage/plot/plot3d/base.c:20856)
    scene = self._rich_repr_jmol(**opts)
  File "sage/plot/plot3d/base.pyx", line 261, in sage.plot.plot3d.base.Graphics3d._rich_repr_jmol (build/cythonized/sage/plot/plot3d/base.c:7224)
    if not jdata.is_jvm_available():
  File "/ext/sage/sage-9.0/local/lib/python3.7/site-packages/sage/interfaces/jmoldata.py", line 70, in is_jvm_available
    java_version_number = int(re.sub(r'.*version "(0\.|1\.)?(\d*)[\s\S]*', r'\2', version))
ValueError: invalid literal for int() with base 10: 'Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/home/user/tmp -Xms64m\n11'
```

This is *ALSO* broken on the command line with straight sage, so has nothing to do with sage worksheets.

Also, note that [sage-9.0 breaks sagetex as well for different reasons](https://github.com/sagemathinc/cocalc/issues/4432)...

Reported upstream: https://trac.sagemath.org/ticket/29281

**Comment by williamstein** [comment]
WORKAROUND: Type `sage_select 8.9`.

**Comment by williamstein** [comment]
This did get fixed upstream -- just has to get merged into an upcoming sage release.

**Comment by fchapoton** [comment]
can be closed now ?

**Comment by williamstein** [comment]
closing!  thanks.
