### ISSUE TITLE
syncstring maintenance crash

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#4913]
today, I watched syncstring maintenance closely. I saw an error happen twice, which might or might not be harmful. In any case, I would expect that it just catches the exception – maybe waits a bit (the loop timeout) – and tries again.

The DB had no load issues, and well, as far as I can tell everything is ok ... after a restart it continues to do its job.

```
2020-10-04T14:01:00.355Z - debug: PostgreSQL._query('SELECT NOW()',id='813383'): "done (concurrent=0) (query_time_ms=116) -- success"
2020-10-04T14:01:00.355Z - debug: PostgreSQL.test_query: "finished"
2020-10-04T14:01:02.489Z - debug: PostgreSQL.save_blob(uuid='074e514f-6c05-489c-b073-732c7718580f'): "nothing in DB, so we insert the blob."
2020-10-04T14:01:02.501Z - debug: PostgreSQL._query('INSERT INTO blobs',id='97833e'): "query='INSERT INTO blobs (\"id\",\"blob\",\"project_id\",\"count\",\"size
\",\"created\",\"compress\") VALUES  ($1,$2,$3,$4,$5,$6,$7)  (concurrent=1)'"
2020-10-04T14:01:02.704Z - debug: PostgreSQL._query('INSERT INTO blobs',id='97833e'): "done (concurrent=0) (query_time_ms=203) -- success"
2020-10-04T14:01:02.704Z - debug: PostgreSQL.archive_patches(string_id='ac88cd41041edf45ba9d13f625759e0a7526eeec'): "update syncstring to indicate patches have
been archived in a blob"
2020-10-04T14:01:02.704Z - debug: PostgreSQL._query('UPDATE syncstrings',id='58fbac'): "query='UPDATE syncstrings SET \"archived\"=$1 WHERE string_id = $2::CHAR
(40) (concurrent=1)'"
2020-10-04T14:01:02.707Z - debug: PostgreSQL._query('UPDATE syncstrings',id='58fbac'): "done (concurrent=0) (query_time_ms=3) -- success"
2020-10-04T14:01:02.707Z - debug: PostgreSQL.archive_patches(string_id='ac88cd41041edf45ba9d13f625759e0a7526eeec'): "actually delete patches"
2020-10-04T14:01:02.707Z - debug: PostgreSQL._query('DELETE FROM patches',id='bc459c'): "query='DELETE FROM patches WHERE string_id = $1::CHAR(40) (concurrent=1
)'"
2020-10-04T14:02:00.239Z - debug: PostgreSQL.test_query: "starting"
2020-10-04T14:02:00.239Z - debug: PostgreSQL._query('SELECT NOW()',id='fe7bb2'): "query='SELECT NOW() (concurrent=2)'"
2020-10-04T14:02:02.708Z - debug: PostgreSQL._do_connect: "error -- timeout"
2020-10-04T14:02:02.709Z - debug: PostgreSQL.connect: "will try to connect"
2020-10-04T14:02:02.709Z - debug: PostgreSQL.connect: "until successful"
2020-10-04T14:02:02.710Z - debug: PostgreSQL.connect: "retry_until_success() -- try 1"
2020-10-04T14:02:02.710Z - debug: PostgreSQL._do_connect: "connect to db"
2020-10-04T14:02:02.710Z - debug: PostgreSQL._do_connect: "assuming database exists"
2020-10-04T14:02:02.711Z - debug: PostgreSQL._query('DELETE FROM patches',id='bc459c'): "error_listener fired"
2020-10-04T14:02:02.711Z - debug: PostgreSQL._query('DELETE FROM patches',id='bc459c'): "done (concurrent=-1), (query_time_ms=60004) -- error: error"
Error: error in syncstring_maintenance -- postgresql error
    at Object.cb (/cocalc/src/smc-hub/kucalc/maintenance-syncstrings.coffee:64:15)
    at /cocalc/src/smc-hub/postgres-blobs.js:1007:57
    at /cocalc/src/smc-hub/node_modules/async/lib/async.js:726:13
    at /cocalc/src/smc-hub/node_modules/async/lib/async.js:52:16
    at /cocalc/src/smc-hub/node_modules/async/lib/async.js:264:21
    at /cocalc/src/smc-hub/node_modules/async/lib/async.js:44:16
    at /cocalc/src/smc-hub/node_modules/async/lib/async.js:723:17
    at /cocalc/src/smc-hub/node_modules/async/lib/async.js:167:37
    at /cocalc/src/smc-hub/node_modules/async/lib/async.js:52:16
    at /cocalc/src/smc-hub/node_modules/async/lib/async.js:361:13
    at /cocalc/src/smc-hub/node_modules/async/lib/async.js:52:16
    at /cocalc/src/smc-hub/node_modules/async/lib/async.js:322:29
    at /cocalc/src/smc-hub/node_modules/async/lib/async.js:44:16
    at /cocalc/src/smc-hub/node_modules/async/lib/async.js:358:17
    at Object.cb (/cocalc/src/smc-hub/postgres-blobs.js:992:28)
    at /cocalc/src/smc-hub/postgres-blobs.js:1128:55
    at /cocalc/src/smc-hub/node_modules/async/lib/async.js:726:13
    at /cocalc/src/smc-hub/node_modules/async/lib/async.js:52:16
    at /cocalc/src/smc-hub/node_modules/async/lib/async.js:264:21
    at /cocalc/src/smc-hub/node_modules/async/lib/async.js:44:16
[...]
```

**Comment by williamstein** [comment]
A while ago one of us rewrote the patch deletion to be done in a loop with throttling to address this.
