### ISSUE TITLE
ipynb→pdf: broken for filenames like foo[AS-3A].ipynb

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#5365]
1. create a notebook named `foo[AS-3A].ipynb` or similar
2. file → export pdf via latex
3. nbconvert fails ... either it's an upstream bug or somehow the filename isn't passed down correctly.

workaround: rename your file or duplicate it. those square brackets seem to trigger a search pattern.

if that's truly in nbconvert (i.e. it tries to be smart) we have to switch to a temporary filename to avoid this – or maybe there is a command line option to disable this?

```
Error: Traceback (most recent call last):
  File "/usr/local/bin/jupyter-nbconvert", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/jupyter_core/application.py", line 270, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/traitlets/config/application.py", line 663, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/usr/local/lib/python3.8/dist-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/nbconvert/nbconvertapp.py", line 285, in initialize
    self.init_notebooks()
  File "/usr/local/lib/python3.8/dist-packages/nbconvert/nbconvertapp.py", line 314, in init_notebooks
    globbed_files = glob.glob(pattern)
  File "/usr/lib/python3.8/glob.py", line 21, in glob
    return list(iglob(pathname, recursive=recursive))
  File "/usr/lib/python3.8/glob.py", line 57, in _iglob
    yield from _glob1(dirname, basename, dironly)
  File "/usr/lib/python3.8/glob.py", line 85, in _glob1
    return fnmatch.filter(names, pattern)
  File "/usr/lib/python3.8/fnmatch.py", line 52, in filter
    match = _compile_pattern(pat)
  File "/usr/lib/python3.8/fnmatch.py", line 46, in _compile_pattern
    return re.compile(res).match
  File "/usr/lib/python3.8/re.py", line 252, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python3.8/re.py", line 304, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.8/sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.8/sre_parse.py", line 948, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "/usr/lib/python3.8/sre_parse.py", line 443, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "/usr/lib/python3.8/sre_parse.py", line 834, in _parse
    p = _parse_sub(source, state, sub_verbose, nested + 1)
  File "/usr/lib/python3.8/sre_parse.py", line 443, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "/usr/lib/python3.8/sre_parse.py", line 598, in _parse
    raise source.error(msg, len(this) + 1 + len(that))
re.error: bad character range S-3 at position 9
```

**Comment by haraldschilly** [comment]
command line only gives the same problem. `jupyter nbconvert --to pdf foo\[AS-3A\].ipynb`

ok, I found https://github.com/jupyter/nbconvert/issues/911

seems like we have to replace all `[` and `]` by `[[]` and `[]]` 🤷🏻
