### ISSUE TITLE
hub<->db reconnection issues

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#5431]
setup: 
-  in my dev project, HEAD at 066abd124a9d91d2d, clean tree and a recent `run make`
- open dev page, well, hub log looks fine, so far so good
- I  even tried to change this by deleting the compile caches in `/tmp/...` ... same result.

then I stopped postgres,waited 5 - 10 seconds, and started it again. I saw various problems

1.  after about 2 such database restart cycles
```
Failed to connect to database -- ALL clients failed to connect
Segmentation fault (core dumped)
```

2. During another try, I see several disconnect messages at once, e.g.
```
Failed to connect to database -- ALL clients failed to connect
Failed to connect to database -- ALL clients failed to connect
Failed to connect to database -- ALL clients failed to connect
```

3. I don't have the logs any more, but last week I tried this briefly and it ended up in some sort of endless loop trying to reconnect. So, maybe exactly where it segfaults now, a callback or promise errored out earlier.

In any case, the background of all of that is related to the recent database updates. The websocket services were partially broken after the database restart.

The expected result would be to neither cause "segfaults" or "infinite loops" when trying to reconnect to the DB.

**Comment by haraldschilly** [comment]
ad 3: when checking out `9a5ba4fb41e16a6`, I can reproduce that "infinite loop". same as above:

```
2021-08-02T12:20:17.143Z:   cocalc:debug:primus Client(IwixFRyJcAL9KyBWvZng_).push_to_client: [1 mesg_time_ms]  [18 mesg_avg_ms] -- mesg.id=fe13b68e-3a36-4e04-b000-e23690f28dfb +2s

FATAL:  terminating connection due to administrator command
FATAL:  terminating connection due to administrator command
Failed to connect to database -- ALL clients failed to connect
Failed to connect to database -- ALL clients failed to connect
Failed to connect to database -- ALL clients failed to connect
2021-08-02T12:20:27.667Z:   cocalc:debug:postgres PostgreSQL._do_connect: "error -- Error: connection not open\n" +32s

WARNING -- error handling mentions -- postgresql Error: Connection terminated
/home/user/cocalc/src/smc-hub/mentions/handle.ts:58
      console.trace();
              ^

Trace
    at Object.<anonymous> (/home/user/cocalc/src/smc-hub/mentions/handle.ts:58:15)
    at null.step (/home/user/cocalc/src/smc-hub/mentions/handle.ts:4:4)
    at Object.throw (/home/user/cocalc/src/smc-hub/mentions/handle.ts:4:4)
    at null.rejected (/home/user/cocalc/src/smc-hub/mentions/handle.ts:4:4)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at runNextTicks (internal/process/task_queues.js:64:3)
    at processImmediate (internal/timers.js:437:9)
init_start_always_running_projects postgresql Error: Connection terminated
2021-08-02T12:20:27.683Z:   cocalc:debug:postgres PostgreSQL._do_connect: "error -- Error: connection not open\n" +16ms

2021-08-02T12:20:27.691Z:   cocalc:debug:postgres PostgreSQL._do_connect: "error -- Error: connection not open\n" +8ms

2021-08-02T12:20:27.696Z:   cocalc:debug:postgres PostgreSQL._do_connect: "error -- Error: connection not open\n" +5ms

2021-08-02T12:20:27.701Z:   cocalc:debug:postgres PostgreSQL._do_connect: "error -- Error: connection not open\n" +5ms

2021-08-02T12:20:27.706Z:   cocalc:debug:postgres PostgreSQL._do_connect: "error -- Error: connection not open\n" +5ms

2021-08-02T12:20:27.711Z:   cocalc:debug:postgres PostgreSQL._do_connect: "error -- Error: connection not open\n" +4ms

2021-08-02T12:20:27.718Z:   cocalc:debug:postgres PostgreSQL._do_connect: "error -- Error: connection not open\n" +8ms

2021-08-02T12:20:27.722Z:   cocalc:debug:postgres PostgreSQL._do_connect: "error -- Error: connection not open\n" +4ms

2021-08-02T12:20:27.726Z:   cocalc:debug:postgres PostgreSQL._do_connect: "error -- Error: connection not open\n" +4ms

2021-08-02T12:20:27.730Z:   cocalc:debug:postgres PostgreSQL._do_connect: "error -- Error: connection not open\n" +4ms

2021-08-02T12:20:27.736Z:   cocalc:debug:postgres PostgreSQL._do_connect: "error -- Error: connection not open\n" +6ms

2021-08-02T12:20:27.740Z:   cocalc:debug:postgres PostgreSQL._do_connect: "error -- Error: connection not open\n" +4ms

[...]
```

that last line runs every few milliseconds, and there are thousands

**Comment by haraldschilly** [comment]
4. while testing this more often (I tried to bisect the error, but it's too tedious), I saw yet another variation: log ends like that, then the hub stops.

```
2021-08-02T12:32:06.812Z:   cocalc:debug:postgres PostgreSQL._ensure_database_exists: "ensure database 'smc' exists" +0ms

2021-08-02T12:32:06.812Z:   cocalc:debug:postgres PostgreSQL._ensure_database_exists: "psql --user smc --host /home/user/cocalc/src/smc-hub/../data/postgres/socket --port 5432 --list --tuples-only" +0ms

2021-08-02T12:32:06.812Z:   cocalc:debug:execute-code execute_code: "psql --user smc --host /home/user/cocalc/src/smc-hub/../data/postgres/socket --port 5432 --list --tuples-only" +9s

2021-08-02T12:32:06.813Z:   cocalc:debug:postgres PostgreSQL._query('INSERT INTO hub_servers',id='008c65'): "error_listener fired" +1ms

2021-08-02T12:32:06.813Z:   cocalc:debug:postgres PostgreSQL._query('INSERT INTO hub_servers',id='008c65'): "done (concurrent=-1), (query_time_ms=11) -- error: error" +0ms

2021-08-02T12:32:06.813Z:   cocalc:debug:hub register_hub -- fail - postgresql error +10ms

2021-08-02T12:32:06.814Z:   cocalc:debug:postgres PostgreSQL._query('INSERT INTO hub_servers',id='008c65'): "called when finished (ignoring)" +1ms

postgresql error
2021-08-02T12:32:06.815Z:   cocalc:error:hub Error --  postgresql error +0ms

~/cocalc/src$ 
```

**Comment by williamstein** [comment]
I was able to reproduce this.

**Comment by williamstein** [comment]
There are two different things going on here. Unfortunately, the segfault seems to just be a bug in pg-native (see https://github.com/brianc/node-pg-native).   Numerous people hit this error:

https://github.com/brianc/node-pg-native/issues/70#issuecomment-505502480

E.g., "The solution was to simply use pg instead of pg-native."

The bug is closed as "wontfix".  

I think pg-native is simply a faster interface to pg and there is a pure javascript one that doesn't segfault.  pg-native hasn't been updated in over 3 years, whereas the javascript pg interface was updated a week ago... so maybe we should just switch.  I have no evidence the speed difference matters, and the docs don't say either.

**Comment by williamstein** [comment]
Oh, I have a comment in our source code "it can be 5x slower or more!" in reference to non-native version.

**Comment by williamstein** [comment]
I think this thread says performance of pg versus pg-native used to be bad, but now pg is much better: https://github.com/brianc/node-postgres/issues/1993
