### ISSUE TITLE
next: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#5535]
saw this in the logs:

```
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at __node_internal_captureLargerStackTrace (internal/errors.js:412:5)
    at __node_internal_addCodeToName (internal/errors.js:168:9)
    at new NodeError (internal/errors.js:322:7)
    at ServerResponse.setHeader (_http_outgoing.js:561:11)
    at Server.renderError (/cocalc/lib/node_modules/@cocalc/hub/node_modules/next/server/next-server.ts:1973:11)
    at Server.render404 (/cocalc/lib/node_modules/@cocalc/hub/node_modules/next/server/next-server.ts:2133:17)
    at Server.renderToResponseWithComponents (/cocalc/lib/node_modules/@cocalc/hub/node_modules/next/server/next-server.ts:1830:20)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at Server.renderToResponse (/cocalc/lib/node_modules/@cocalc/hub/node_modules/next/server/next-server.ts:1894:39)
    at Server.pipe (/cocalc/lib/node_modules/@cocalc/hub/node_modules/next/server/next-server.ts:1262:18)
    at Object.fn (/cocalc/lib/node_modules/@cocalc/hub/node_modules/next/server/next-server.ts:986:14)
    at Router.execute (/cocalc/lib/node_modules/@cocalc/hub/node_modules/next/server/router.ts:346:21)
    at Server.run (/cocalc/lib/node_modules/@cocalc/hub/node_modules/next/server/next-server.ts:1229:20)
    at Server.handleRequest (/cocalc/lib/node_modules/@cocalc/hub/node_modules/next/server/next-server.ts:487:10) {
  code: 'ERR_HTTP_HEADERS_SENT'
}
```

**Comment by williamstein** [comment]
This is still happening.  I'm not sure to what extent it is something to worry about.

**Comment by williamstein** [comment]
Closing this due to lack of activity and concern.
