### ISSUE TITLE
jupyter: convert via latex to pdf claims error, but all good

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#6129]
make a jupyter notebook, select "export via latex to PDF", which starts the "save and download pdf via nbconvert and latex" progress dialog.

wait a bit (maybe we should increase the timeout, IIRC it failed once with a plain "Error"), and then it says:

![Screenshot from 2022-09-14 18-45-32](https://user-images.githubusercontent.com/207405/190214010-9c40ddbf-45ef-4529-a16d-48e30226990c.png)

this happens for nbconvert 6.5 something and the newer 7.0 version

**plot twist**: there is a `[name].pdf` file, and everything is actually fine

**Comment by williamstein** [comment]
I tried to reproduce this in a few projects and was unable to see any error.  It just worked perfectly.  Maybe there was something funny in the particular project you were using?

**Comment by haraldschilly** [comment]
hmm. it's fine for me as well. my suspicion is, this error was specific to the notebook. in any case, let's close this, we know that any kind of latex processing is never 100% perfect.

**Comment by daholzfeind** [comment]
Hi @haraldschilly , 

I might have a similar error. I am not able to export Notebooks as PDF via LaTeX anymore. Cocalc suggests me to restart the project, but it does not help. This is the promted error message: 

```python
Error: Traceback (most recent call last):
  File "/usr/local/bin/jupyter-nbconvert", line 5, in <module>
    from nbconvert.nbconvertapp import main
  File "/home/user/.local/lib/python3.8/site-packages/nbconvert/__init__.py", line 4, in <module>
    from .exporters import *
  File "/home/user/.local/lib/python3.8/site-packages/nbconvert/exporters/__init__.py", line 3, in <module>
    from .html import HTMLExporter
  File "/home/user/.local/lib/python3.8/site-packages/nbconvert/exporters/html.py", line 23, in <module>
    from nbconvert.filters.highlight import Highlight2HTML
  File "/home/user/.local/lib/python3.8/site-packages/nbconvert/filters/__init__.py", line 6, in <module>
    from .markdown import *
  File "/home/user/.local/lib/python3.8/site-packages/nbconvert/filters/markdown.py", line 13, in <module>
    from .markdown_mistune import markdown2html_mistune
  File "/home/user/.local/lib/python3.8/site-packages/nbconvert/filters/markdown_mistune.py", line 31, in <module>
    class MathBlockGrammar(mistune.BlockGrammar):
AttributeError: module 'mistune' has no attribute 'BlockGrammar'
```

**Comment by haraldschilly** [comment]
@daholzfeind the first thing I notice is there are locally installed packages: `/home/user/.local/lib/python3.8/site-packages/nbconvert` 

So, I don't know what else is there, but one drastic thing to do is to clean out everything locally installed. `rm -rf /home/user/.local/lib/python3.8`

Because then the `jupyter-nbconvert` will load the globally installed nbconvert lib + dependencies.

**Comment by daholzfeind** [comment]
@haraldschilly Yes, you are right. I had to manually install nbconvert due to another issue, we've discussed it in Discord in the past. Anyhow, I removed the local installed packages, as you suggested and reinstalled `scikit-fem`, since it's not globnally available. 

Converting the notebook again yields to a new issue: 
```python
Error: [NbConvertApp] Converting notebook firstExample.ipynb to pdf
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/traitlets/traitlets.py", line 537, in get
    value = obj._trait_values[self.name]
KeyError: 'command'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/traitlets/traitlets.py", line 537, in get
    value = obj._trait_values[self.name]
KeyError: 'inkscape_version'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/jupyter-nbconvert", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/jupyter_core/application.py", line 269, in launch_instance
    return super().launch_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/traitlets/config/application.py", line 846, in launch_instance
    app.start()

[ ... trunk ] 

  File "/usr/local/lib/python3.8/dist-packages/traitlets/traitlets.py", line 977, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/nbconvert/preprocessors/svg2pdf.py", line 60, in _inkscape_version_default
    raise RuntimeError("Unable to find inkscape executable --version")
RuntimeError: Unable to find inkscape executable --version
```
And this error, was the reasong why I rolled back the nbconvert version. You can re-read our discussion in Discord from the 28th of October, 2020.  🙂

This time I did not change any kind of plot mimetype in the Notebook settings btw.
