### ISSUE TITLE
sagews: animations can't be displayed

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#6219]
This worked in 9.6, but broke with 9.7:

```
x = SR.var("x")
sines = [plot(c*sin(x), (-2*pi,2*pi), color=Color(c,0,0), ymin=-1, ymax=1) for c in sxrange(0,1,.2)]
a = animate(sines)
a.show()
```

stacktrace:

```
Error in lines 1-1
Traceback (most recent call last):
  File "/cocalc/lib/python3.9/site-packages/smc_sagews/sage_server.py", line 1230, in execute
    exec(
  File "", line 1, in <module>
  File "/cocalc/lib/python3.9/site-packages/smc_sagews/sage_salvus.py", line 2972, in show
    s = show0(objs, combine_all=True)
  File "/cocalc/lib/python3.9/site-packages/smc_sagews/sage_salvus.py", line 2931, in show0
    b = show0(a)
  File "/cocalc/lib/python3.9/site-packages/smc_sagews/sage_salvus.py", line 2891, in show0
    show_animation(obj, **kwds)
  File "/cocalc/lib/python3.9/site-packages/smc_sagews/sage_salvus.py", line 2643, in show_animation
    salvus.file(t, raw=True)
  File "/cocalc/lib/python3.9/site-packages/smc_sagews/sage_server.py", line 974, in file
    raise ValueError(
ValueError: can only send raw files in your home directory
```

WORKAROUND: use a jupyter notebook with the sage 9.7 kernel

**Comment by williamstein** [comment]
My guess is this is caused by temp moving from ~/.sage to /tmp

**Comment by williamstein** [comment]
The other MUCH less invasive workaround is to use Sage-9.6 and continue to use your Sage worksheets.  Use sage_select in the terminal to change which version of sage you use in a given project.

**Comment by williamstein** [comment]
The trick to work on smc_sagews these days on cocalc.com in a dev project is to set the PYTHONPATH in project settings for the project running in your dev server:
<img width="844" alt="image" src="https://user-images.githubusercontent.com/1276278/204060842-23628722-f15c-4e57-b0ba-77c330abb529.png">

```json
{
  "PYTHONPATH": "/home/user/cocalc/src/smc_sagews"
}
```

Then when you start that project you can confirm in the terminal that PYTHONPATH is set.  When you start a sage worksheet, confirm that the smc_sagews library is coming from /home/user...
```py
import smc_sagews
help(smc_sagews)
```
