### ISSUE TITLE
project/jupyter: registering process exit listener too often

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#6696]
The error below happens here, when I'm testing nbgrader:

```
export class JupyterKernel
[...]
  constructor(
[...]
    process.on("exit", () => {             <<<<<<<<<<<<<<<<<<<<<
      if (this._kernel != null) {
        killKernel(this._kernel);
      }
    });
```

```
(node:8) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added to [process]. Use emitter.setMaxListeners() to increase limit
    at _addListener (node:events:587:17)
    at process.addListener (node:events:605:10)
    at new JupyterKernel (/cocalc/github/src/packages/project/dist/jupyter/jupyter.js:197:17)
    at kernel (/cocalc/github/src/packages/project/dist/jupyter/jupyter.js:144:12)
    at Object.init_jupyter0 [as f] (/cocalc/github/src/packages/project/dist/nbgrader/jupyter-run.js:48:40)
```

---

Somewhere else there is also `process.removeListener("exit", this.close);` which I don't get, where is `this.close` registered?

I any case, maybe we should just remove this, because there is also a `nodeCleanup` iterating over all kernels.

**Comment by haraldschilly** [comment]
this should be addressed, but we should stay alert to similar warnings
