### ISSUE TITLE
uncaught exceptions in the hub -- TypeError: p.sslConfigToPsqlEnv is not a function

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#7381]
```
{
  "id": "892b770a-a9cd-4447-bdd0-38934f131461",
  "event": "uncaught_exception",
  "value": {
    "host": "hub-next-785959f998-pqkp4",
    "error": "TypeError: p.sslConfigToPsqlEnv is not a function",
    "stack": "TypeError: p.sslConfigToPsqlEnv is not a function\n    at i._ensure_database_exists (/cocalc/src/packages/next/.next/server/chunks/6447.js:3:1665)\n    at u.series.r.hosts (/cocalc/src/packages/next/.next/server/chunks/6447.js:1:8168)\n    at /cocalc/src/packages/next/.next/server/chunks/5788.js:7:2770\n    at s (/cocalc/src/packages/next/.next/server/chunks/5788.js:7:5605)\n    at a.forEachOfSeries.a.eachOfSeries (/cocalc/src/packages/next/.next/server/chunks/5788.js:7:5709)\n    at Z (/cocalc/src/packages/next/.next/server/chunks/5788.js:7:2750)\n    at a.series (/cocalc/src/packages/next/.next/server/chunks/5788.js:7:8967)\n    at i._connect (/cocalc/src/packages/next/.next/server/chunks/6447.js:1:8100)\n    at i (/cocalc/src/packages/next/.next/server/chunks/4006.js:1:23988)\n    at t.retry_until_success (/cocalc/src/packages/next/.next/server/chunks/4006.js:1:24632)"
  },
  "time": "2024-03-19T20:51:41.890Z"
}
```

I don't understand this, but @schrodingersket recently introduced sslConfigToPsqlEnv, so maybe he will?

**Comment by williamstein** [comment]
NOTE: This doesn't necessarily cause any serious problems at runtime -- it just happened once or twice and could have a "destabilizing influence" and that's not it.  So NOT a high priority to fix!
