### ISSUE TITLE
new uncaught exception happening in the hub -- 

### ISSUE THREAD

**Issue by williamstein** [sagemathinc/cocalc#7436]
This happened a couple of times in the last 24 hours.  I don't think it is caused by any recent change.  @haraldschilly maybe you can easily fix it?

```js
{
  "id": "a10698f4-053b-459d-9916-92a0253ccb57",
  "event": "uncaught_exception",
  "value": {
    "host": "hub-next-77c59bb975-zp5ss",
    "error": "TypeError: Cannot read properties of undefined (reading 'givenName')",
    "stack": "TypeError: Cannot read properties of undefined (reading 'givenName')
    at first_name (/cocalc/src/packages/server/auth/sso/public-strategies.ts:57:43)
    at <anonymous> (/cocalc/src/packages/server/hub/auth.ts:633:15)
    at Layer.handle [as handle_request] (/cocalc/src/packages/node_modules/.pnpm/express@4.19.2/node_modules/express/lib/router/layer.js:95:5)
    at next (/cocalc/src/packages/node_modules/.pnpm/express@4.19.2/node_modules/express/lib/router/route.js:149:13)
    at complete (/cocalc/src/packages/node_modules/.pnpm/passport@0.6.0/node_modules/passport/lib/middleware/authenticate.js:271:13)
    at /cocalc/src/packages/node_modules/.pnpm/passport@0.6.0/node_modules/passport/lib/middleware/authenticate.js:278:15
    at pass (/cocalc/src/packages/node_modules/.pnpm/passport@0.6.0/node_modules/passport/lib/authenticator.js:428:14)
    at Authenticator.transformAuthInfo (/cocalc/src/packages/node_modules/.pnpm/passport@0.6.0/node_modules/passport/lib/authenticator.js:450:5)
    at /cocalc/src/packages/node_modules/.pnpm/passport@0.6.0/node_modules/passport/lib/middleware/authenticate.js:275:22
    at /cocalc/src/packages/node_modules/.pnpm/passport@0.6.0/node_modules/passport/lib/http/request.js:41:7"
  },
  "time": "2024-04-11T01:37:29.522Z"
}
```

**Comment by haraldschilly** [comment]
Hmm, something must have changed with google's OAuth2. I added a note and an idea to switch this a year ago. I'll try that now.

**Comment by haraldschilly** [comment]
But interestingly, right now Google SSO is not broken.

**Comment by williamstein** [comment]
> Interestingly, right now Google SSO is not broken.

I saw it happen a few times with that stacktrace, but not regularly.  It's very likely a case where one of us made an assumption about what the Google SSO returns and it is wrong in some edge case.  What about changing the code to this (note the ?'s):

```ts
export const GoogleStrategyConf: StrategyConf = {
  name: "google",
  type: googleSSOtype,
  PassportStrategyConstructor: useMainGoogleSSO
    ? GoogleStrategy
    : GoogleStrategyOld,
  auth_opts: { scope: "openid email profile" },
  login_info: {
    id: (profile) => profile.id,
    first_name: (profile) => profile.name?.givenName ?? "Anonymous",
    last_name: (profile) => profile.name?.familyName ?? "User",
    emails: (profile) => profile.emails?.map((x) => x.value as string) ?? [],
  },
};
```

**Comment by haraldschilly** [comment]
That's fine with me
