### ISSUE TITLE
strange crash when refreshing cocalc frontend

### ISSUE THREAD

**Issue by haraldschilly** [sagemathinc/cocalc#7993]
```
TypeError: Cannot read properties of undefined (reading 'set_log_level')
    at inline_js (eval at javascript_eval (https://cocalc.com/static/89c4a43e7b5b998e6ee4.js:1:29722), <anonymous>:168:13)
    at run_inline_js (eval at javascript_eval (https://cocalc.com/static/89c4a43e7b5b998e6ee4.js:1:29722), <anonymous>:177:24)
    at eval (eval at javascript_eval (https://cocalc.com/static/89c4a43e7b5b998e6ee4.js:1:29722), <anonymous>:227:2)
    at eval (eval at javascript_eval (https://cocalc.com/static/89c4a43e7b5b998e6ee4.js:1:29722), <anonymous>:20:11)
    at Array.forEach (<anonymous>)
    at run_callbacks (eval at javascript_eval (https://cocalc.com/static/89c4a43e7b5b998e6ee4.js:1:29722), <anonymous>:18:36)
    at on_load (eval at javascript_eval (https://cocalc.com/static/89c4a43e7b5b998e6ee4.js:1:29722), <anonymous>:52:9)
    at load_libs (eval at javascript_eval (https://cocalc.com/static/89c4a43e7b5b998e6ee4.js:1:29722), <anonymous>:103:4)
    at load_or_wait (eval at javascript_eval (https://cocalc.com/static/89c4a43e7b5b998e6ee4.js:1:29722), <anonymous>:225:7)
    at https://cocalc.com/static/app-ae3cdde41cf48f605356.js?939bbd8f11e1fda200ff:4384:4826094
```

**Comment by haraldschilly** [comment]
It's a jupyter notebook, so, maybe there is stuff in it that causes this. I can dismiss it, thugh. It happens when I scroll the notebook as well.

**Comment by haraldschilly** [comment]
Edit → clear all cell output fixes it.

So, not sure what to do. Maybe such errors in a jupyter notebook should fail silently?

**Comment by williamstein** [comment]
run_inline_js is not in our codebase.

Our code to run javascript in a notebook puts it in a try/catch and returns the error.  Thus my guess is that this inline_js stuff, whatever it is, is being run async so can't be caught. 

> Maybe such errors in a jupyter notebook should fail silently?

We can add `javascript_eval` to the error report whitelist.   The function isWhitelisted is in src/packages/static/src/webapp-error.ts    You can add something to javascript_eval, then try and see what happens.  I would, but you didn't provide a way to reproduce this here.

**Comment by williamstein** [comment]
[plotly.ipynb.sage-jupyter2.txt](https://github.com/user-attachments/files/17637243/plotly.ipynb.sage-jupyter2.txt)
[plotly.ipynb.txt](https://github.com/user-attachments/files/17637244/plotly.ipynb.txt)

To reproduce, put the attached files  in a cocalc project, then rename them:
```sh
mv plotly.ipynb.sage-jupyter2.txt .plotly.ipynb.sage-jupyter2
mv plotly.ipynb.txt plotly.ipynb
```

and open `plotly.ipynb`, but do NOT run any code. It crashed for me.
